### ISSUE TITLE
Permalinks to a rom

### ISSUE THREAD

**Issue by daedric7** [linuxserver/emulatorjs#107]
Not a issue, but a question:

Is it possible to have a permalink to one of the roms ?

**Comment by thelamer** [comment]
Like a web address?

**Comment by daedric7** [comment]
> Like a web address?

Correct, a URL to download the refered rom directly.

**Comment by thelamer** [comment]
So no this is not currently possible, keep in mind this application ingests everything clientside so the endpoint URL would need wide open CORS rules to function properly. 
In general this is meant to be a self hosted solution, if you are looking for stuff that ingests cloud URLs or stuff off the internet I would highly recommend looking at these: 
https://github.com/BinBashBanana/webretro
https://github.com/EmulatorJS/EmulatorJS
https://github.com/webrcade/webrcade
