### ISSUE TITLE
Saturn Problem

### ISSUE THREAD

**Issue by Weels92** [linuxserver/emulatorjs#108]
Hello, i've installed Emulatorjs on docker, everything is working but when i launch a Saturn game , the game is loading but after that i've the Saturn bios screen with drive empty (with mozilla or chrome) someone have an idea on this ?
![Capture](https://github.com/linuxserver/emulatorjs/assets/94567748/71f6bed8-7e7d-426c-8aaa-d3d3373d121c)

**Comment by Sh33n** [comment]
It means your game is not recognized by the emulator.
I advise you to download .chd format for roms and forget all cue / ccd / iso / mds / etc...
With .chd all works like a charm.

**Comment by Weels92** [comment]
Hahaha !
True !
Works like a charm.

Thanks a lot Sh33n
