### ISSUE TITLE
Multiple questions about customization / updating

### ISSUE THREAD

**Issue by Sh33n** [linuxserver/emulatorjs#109]
Hello,

I've deployed linuxserver/emulatorjs and created my own game library, it's a great application, thank you for it, sad it's no more maintained anymore.

I have a few questions regarding the setup : 

- I'd like to change some arts for roms but I can't. For example, if the rom is detected as Europe, emulatorjs will download videos and logo for the Europe version of the rom. Problem is most of the time, there are no assets for the Europe version but there are assets for USA version.
So I'd like to tell to the database to fetch the USA version of assets for this European rom, but I don't know how to proceed. When game is undetected, you can choose what is the rom in a list, when game is detected you can't choose version of the rom, you're stuck with what has been detected.

- How to upload new shaders in system folder ? The roms folder is mounted by docker, but the system folder is not and I don't know how to interact with it. I can't find the system folder inside docker shell, is it a part of the obfuscation ?

- I think it's not possible, but I still can ask. Is there  a way to upgrade core ?

Thanks.

**Comment by mattheys** [comment]
> I'd like to change some arts for roms but I can't. For example, if the rom is detected as Europe, emulatorjs will download videos and logo for the Europe version of the rom. Problem is most of the time, there are no assets for the Europe version but there are assets for USA version.
So I'd like to tell to the database to fetch the USA version of assets for this European rom, but I don't know how to proceed. When game is undetected, you can choose what is the rom in a list, when game is detected you can't choose version of the rom, you're stuck with what has been detected.

I think you could do this in a couple of ways :-

One would be to mount the `/emulatorjs/metadata` path inside the container to somewhere outside.  Then you could download the metadata files from this repo and delete the entries for the European roms, or duplicate the World/USA entry with the European SHA1 signature, maybe you could write a script to remove any entries that just contain a name so you can manually match them.

Create those updates and submit a pull request, didn't realise this wasn't maintained anymore so not sure that would result in a new build or not.

You could clone this repo, do those updates and build your own docker container, maybe a bit too much work.

**Comment by thelamer** [comment]
This all happens with the reference concept in the metadata, IE: 
https://github.com/linuxserver/emulatorjs/blob/master/metadata/snes.json#L2362
References: 
https://github.com/linuxserver/emulatorjs/blob/master/metadata/snes.json#L6929
For it's art ingest.

But in general from the web interface you can modify any of the art assets if you want by clicking on the rom and uploading the logo/vid manually after identification.

**Comment by paparapapapapa** [comment]
Hello, sorry to resurrect this topic, but I’m also very interested in this and there’s no info whatsoever on shaders for non-power users. 

> * How to upload new shaders in system folder ? The roms folder is mounted by docker, but the system folder is not and I don't know how to interact with it. I can't find the system folder inside docker shell, is it a part of the obfuscation ?
