### ISSUE TITLE
Metadata Json

### ISSUE THREAD

**Issue by mattheys** [linuxserver/emulatorjs#110]
I'd like to write (yet another) Rom manager app (should I call it yarma!?), would it be suitable for me to periodically download the metadata files like this for my own application? https://raw.githubusercontent.com/linuxserver/emulatorjs/master/metadata/nes.json

Is it allowed? I get this is open source but I can't see which license it's published under and I don't want to tread on toes especially since there are other more established ways to do this already. 

I'm interested to know if your EmulatorJs docker container periodically refreshes these files or just waits for an updated version of the container to bundle them in with?

I like the idea of the SHA1 hashes to IPFS hashes for the assets but is there a better way to handle this? For example, have their own repo, use IPNS to point to IPFS versions?

Anyway thanks for reading, love your stuff.

**Comment by thelamer** [comment]
Do whatever you want, full permission.
