### ISSUE TITLE
Unable to change default keymap for keyboard

### ISSUE THREAD

**Issue by laye0619** [linuxserver/emulatorjs#111]
This is awesome docker image for FC games. However, I was wondering if I want to change the default keymap for keyboard. Say, the default is arrow + z,x,a,s. Just want to change to like a,s,d,e etc....

I access the config menu by press F1 during the game, select control->port 1 control which I can see the default keymap. I cannot find where I can set the key with my own.

Thanks.

**Comment by thelamer** [comment]
I just build what libretro has for the cores, what emulator are you specifically referencing ?
