### ISSUE TITLE
Support for older web-browsers

### ISSUE THREAD

**Issue by unclehowell** [linuxserver/emulatorjs#113]
I have an old web-browser on a JVC TV.  It's called Sraf TV Browser. 
It's based on and old version of chromium e.g. chrome version 47. 
Neither EmulatorJS/EmulatorJS nor Linuxserver/EMulatorJS runs on this old browser. 
I had a chat with ethanaobrien at EmulatorJS/EmulatorJS. 
He thinks it's because Javascript es6 syntax/classes wasn't added until chrome version 49. 
His suggestion was to use a solution called Browservice. 
My idea was to include an RTSP webapp and node mobile gamepad controller in your docker image. 
The user experience could then be as follows: 

Step 1: User joins/starts a multi-user local network session             |  Step 2: User launches a Controller (or shared-session game as a Video Stream)
:-------------------------:|:-------------------------:
![Screenshot from 2023-12-24 10-46-44](https://github.com/EmulatorJS/EmulatorJS/assets/10119070/af94d8ba-e9ae-44b4-92a0-73a5728d4ee4) | ![selectone](https://github.com/EmulatorJS/EmulatorJS/assets/10119070/da563416-38dd-4ae2-bc75-9b2a53e8b236)

Mobile Gamepads seem work fine with EmulatorJS, they also automatically assign the player number. 
By casting the session its connected to, over RTSP, would give users on the same local network the ability to play against each other and across multiple screens. 

I'm sure I could fork this repo and get both ideas up and running without too much fuss if it helps.

**Comment by thelamer** [comment]
This will never happen sorry. Current Chrome, Safari, and some light Safari testing is all I will ever do. This project makes heavy use of bleading edge webassembly stuff and will need semi recent browsers to function properly.
