### ISSUE TITLE
[Feature request] Login Page

### ISSUE THREAD

**Issue by update-freak** [linuxserver/emulatorjs#114]
Hi,

it would be good to have an login Page when using the Internal Reverse Proxy in Synology DSM. There is no possibility to use basic authentication with username and passwort in the internal Reverse Proxy Manager.

To replace the intern Reverse Proxy (and then use Authelia or Authentik or SWAG) is very hard and complicated: https://www.reddit.com/r/synology/comments/18prdlc/replacing_the_default_reverse_proxy_on_synology/
-> Option A: macvlan but then Problems with Firewall: https://www.synology-forum.de/threads/authelia-mit-internem-nginx-reverse-proxy-von-synology.130960/
-> Option B: additional VM with Linux

This brings me to the conclusion that adding a login page would be better for the Synology Users. Would be really cool if this could be implemented in future releases.

Linked to
https://github.com/linuxserver/emulatorjs/issues/41
https://github.com/linuxserver/docker-emulatorjs/issues/37

**Comment by gr33k** [comment]
Someone else asked this (more recently) - I suggested using Basic Auth via NGINX here: https://github.com/linuxserver/emulatorjs/issues/119

**Comment by thelamer** [comment]
closing dupe
