### ISSUE TITLE
[Feature Request] Easier button to upload assets

### ISSUE THREAD

**Issue by gr33k** [linuxserver/emulatorjs#115]
I see the instructions for doing a curl, but some of the names have [!] and what not making it a pain...

Could there be an option somewhere to check for any new Assets we upload? Also - I tried to upload them in the interface and it didn't work. I saw someone else mention that we should upload the files directly in to the assets folders, and that DOES work...but would be nice to make it easier to upload and submit these (perhaps more people would do it).

Thanks for the great work on this project! I do hope to see some of the other emulator cores ported if you have the time to do so (https://github.com/BinBashBanana/webretro and other sources - would love ScummVM!)

**Comment by thelamer** [comment]
The core premise around this is once you have uploaded any assets and linked the rom the custom metadata tab in the backend shows the data I would need to add to the metadata here: 
https://github.com/linuxserver/emulatorjs/tree/master/metadata

If you toss that in pastebin and link it in even an issue it can be added, really looking for people that needed to manually link whole collections for unkown sha1 references like so the next person does not have to do that linking: 
```
{
  "7B8ABB3A03809C8F8B5C2DBC45ECBB79FAF234E0": {
    "ref": "C339455D5B1DAE04F77C2EE847D0932ADAF2E84B"
  },
  "BF4F759D239760DA1C86B0A588CAA31A14C85AA9": {
    "ref": "A31F11658B41411A412D5F8735B5D7FBFBAEF5D7"
  },
  "BD806EB365A2921BDAB80467C6F2A724395EDCC4": {
    "ref": "7EE948C0D8E695E1642A8B582C83850D24B15666"
  },
  "EDC0D666BF03C53ED525DD86DB795FC78BDBAD9B": {
    "ref": "F63C1F4D3AFA0FC6BEF12A1F5A911B71261CBEE9"
  },
  "2AD91E2898CB59D8C8E495D67AF673E01D66C1AE": {
    "ref": "848FCD22794526BFD093030C6D6AE6B632D87E4B"
  },
  "CCFF343872F6EA4E97F4738DF3B0A221329941F9": {
    "ref": "CB3E7D0FAFC6A4B05DD24E38611B4C1B486962FF"
  },
  "B4060E56111307A1195BA18AEB6BCD95C7ADA37D": {
    "ref": "289AF72D48C8758BCA46B7FEDEF97A88EA376BDE"
  },
  "D127F58692D9A0416F505653AB3DD73400C32399": {
    "ref": "5901886282B7D12A39853B9CA16B64344D6D555E"
  }
}
```

**Comment by gr33k** [comment]
Ok, so I go to the metadata tab and it shows any metadata I've done. I'll post them here and let me know if this is good please?

3DO: https://paste.thec0de.com/?693c0b960a422e20#GhBJqJHqfSrvne86G1pCgkW1TspoyQ9z22bhk6Xm3i87
Arcade: https://paste.thec0de.com/?33ad06d8e69d680f#B7gdbXQvRK2i7rNZ5ob6X4kfB39bENrUyhhMrjZJpDC3
Atari2600: https://paste.thec0de.com/?bc1b18c2db4416b5#31a78Kaud2A5wSjRdqu2VgZiaDtEbsVCkKY3gbAoaXRW
Atari7800: https://paste.thec0de.com/?612188543179a581#2tg1rQ1x1Yadojj4DTWWYaDT2kPeY7RUikTUR6pUopgU
ColecoVision: https://paste.thec0de.com/?6716299cf08a8d34#C931GntEGp3P4G5vxcbupqkBgzbwwRfmNuYUKjB5uoW2
Gameboy: https://paste.thec0de.com/?5d02b8d1f61c1bb0#H4dfTkT64ia8cWL7uVAAijKrXTrhVvKaGqSGZV6JfuQT
Gameboy Color: https://paste.thec0de.com/?51697202728f7cac#7hmkqEkoBi43ZJ8UhwrVfsMqB6dYm9ggn8hG9d4ZDzba
Lynx: https://paste.thec0de.com/?a84148a5e838cbdb#AybQ8NjVuszTZg7KfcKgjBe4iRRv6r4u6Py8DhnoGQ4k
N64: https://paste.thec0de.com/?e2bc89f3a1739273#Fra8757AkvdvE47SywmsJJYsVeoz8wTX61dUVKLgb4aw
NDS: https://paste.thec0de.com/?d80d71969651c111#EQVUfEvCYVgY8ovosZRL16fNiWLcMzzXg3GK6YorXtVF
NES: https://paste.thec0de.com/?4d199da69d3a4abf#9LbfEoTsF3o6j8zjcLsVqvfVrGdNtRz6zKNbX5pN6uDG
PCE: https://paste.thec0de.com/?7b3b5ab5f7d62fc2#Ho5AFhJ7sAxDNZNfzLhGMLVPMs8qC234PNaQzowYkJKX
PSX: https://paste.thec0de.com/?60b05d8c75c17c43#9o1mZoKo4fuQk5sb1QtbSNy6qZ8ig3yL9a1HbCAUMvuj
SegaCD: https://paste.thec0de.com/?317b4f9dba9c1ff9#7tCCbD5q8df8cCJ81GonwHpyUmgNy4yYkLs6npoSMnZe
SegaGG: https://paste.thec0de.com/?563d2b91c1b9997c#GxrpULZrsefHGwW2VMMmgSaL5ZWL8V4smMVTwrVefgHB
SegaMD: https://paste.thec0de.com/?ed4a2ae46c46ab20#vGKeVBLihD2diL1qvjggoCpfcRCPL6EaYtZEnGMbUSQ
SegaSG: https://paste.thec0de.com/?019823337d15a69b#4yhZYPvzCqfQfxQsxNThS2ohL5T6wn2tsrq4nqnrHNBQ
SegaSaturn: https://paste.thec0de.com/?b33dd7c070042830#6XYjv6cVmHk2KdnvNNynH5ZpziagSdENkrLEkzsTbCf
SNES: https://paste.thec0de.com/?41fca4f61753139d#297kp5NTUcwHhXyaAcgLUk49jF1woCrVLbUAkTAJaVKd
VirtualBoy: https://paste.thec0de.com/?ae996494eff829d2#EkE5NHELkSTfgMEFvoRs8tFpHCC9Bz4zSBR1e51GNAR2
WonderSwan: https://paste.thec0de.com/?7ff31a3d2f6400e3#9iy3aK8k2YmZ8KeGbopgWm8TDAFgQckEJ4jYhvjXwtA8

I've added a few missing logos and videos for a few Virtual Boy games that were missing (trying to complete this small collection so it's perfect for others!). I read on here that you must do some curl to an API for those new assets....I was hoping that step can be removed...or these sha files ... I have port 4001 open. Is there a way you can grab these automagically if we have the port open?

(These are using 0bin on my site. Feel free to use this pastebin clone if you like!)

**Comment by thelamer** [comment]
I have more time slotted this weekend for this project will try to cut a release Sunday

**Comment by thelamer** [comment]
I added everything here in this commit will be cutting a release later today
https://github.com/linuxserver/emulatorjs/commit/0eb869fed47c1b652805c713ce06988832579393
It looks large due to me now sorting the keys. 

Also the in web interface uploading of assets is now functional in the latest image(an ipfs upgrade broke it before( all you need to do is customize your stuff in the webui by clicking on the rom in question and open port 4001 to the world on your container, the metadata will contain the CIDs needed to download the new media.
