### ISSUE TITLE
Controller Issue

### ISSUE THREAD

**Issue by nyteghost** [linuxserver/emulatorjs#12]
OS: Windows 11
Server: Unraid
Controller: Xbox(S) controller
Connection Method of Controller: Bluetooth
Browser:Firefox

I can't seem to use my controller with the emulator. Not sure if it's a windows 11 issue or not. 
I have tested controller with firefox at https://gamepad-tester.com/, and it works there but not in the emulator. 
Works in Chrome.
If there is any other information you need, please let me know!

**Comment by thelamer** [comment]
The controller API code is embedded in RetroArch, more specifically here:
https://github.com/libretro/RetroArch/blob/master/input/drivers/rwebinput_input.c

Just in general I can say I will only ever be testing code on chromium based browsers and Apple's WebKit. This should cover all major devices. That is not to say someone cannot integrate Firefox support, just that I am not going to focus on it.

**Comment by thelamer** [comment]
added notes in latest version about no controller support in firefox.
