### ISSUE TITLE
Add Atari5200

### ISSUE THREAD

**Issue by gr33k** [linuxserver/emulatorjs#120]
I was able to get Atari5200 working (for the most part).

I have it scanning the roms and creating the config file, but haven't got it to open the Rom Management page for it (where you identify/download art/add config etc - if this is an easy fix please suggest where I may need to tweak to attempt auto downloading of art!)

Also, haven't had the time to see why the controls aren't working yet (tested mobile on-screen controls and desktop keyboard)

Wanted to post the files here in case you'd like to add :)

[a5200_libretro.zip](https://github.com/linuxserver/emulatorjs/files/13878700/a5200_libretro.zip)

Added this to index.js: 
`{'name': 'atari5200', 'video_position': 'left:11.5vw;top:31.5vh;width:36vw;height:43vh;'},`
[indexa5200.zip](https://github.com/linuxserver/emulatorjs/files/13878713/indexa5200.zip)
UPDATE: https://github.com/linuxserver/emulatorjs/commit/146b3c20c50742d05db0938a1f2dcd8c7d6bbe2a

(UPDATED to include bios) Sample Config file scan generated:
https://paste.thec0de.com/?aa6f421bf38929f3#AhwdX2xDbApi8LLLDqKJPrTJTTovbRa5ZhFaDGJcrAkh

EDIT: Turns out you don't NEED the bios, but it seems to be 'better' (arguably) if you DO have it. Attaching it here (5200.rom) as zip.
[5200.zip](https://github.com/linuxserver/emulatorjs/files/13881277/5200.zip)

UPDATE: Good source for Atari5200 wallpapers and other cool stuff (I'm not much of an artist guy myself):
https://www.screenscraper.fr/systemeinfos.php?plateforme=40&action=onglet&zone=systemeinfosmedias

Logo for Main also added (need to get video and a few other things)
![atari5200](https://github.com/linuxserver/emulatorjs/assets/5171932/2aa270b5-2ff6-4def-84f9-193d91512361)

**Comment by gr33k** [comment]
This is the error I see in the inspector when attempting to click atari5200 roms under "Rom Management"
![Screen Shot 2024-01-09 at 6 12 30 PM](https://github.com/linuxserver/emulatorjs/assets/5171932/97ade535-409a-4beb-8c0b-f853a812779c)

**Comment by thelamer** [comment]
Will take me a bit for new systems I just got time last weekend for rebuilding the cores and cleaning up some bugs.

**Comment by webysther** [comment]
> I was able to get Atari5200 working (for the most part).
> 
> I have it scanning the roms and creating the config file, but haven't got it to open the Rom Management page for it (where you identify/download art/add config etc - if this is an easy fix please suggest where I may need to tweak to attempt auto downloading of art!)
> 
> Also, haven't had the time to see why the controls aren't working yet (tested mobile on-screen controls and desktop keyboard)
> 
> Wanted to post the files here in case you'd like to add :)
> 
> [a5200_libretro.zip](https://github.com/linuxserver/emulatorjs/files/13878700/a5200_libretro.zip)
> 
> Added this to index.js: `{'name': 'atari5200', 'video_position': 'left:11.5vw;top:31.5vh;width:36vw;height:43vh;'},` [indexa5200.zip](https://github.com/linuxserver/emulatorjs/files/13878713/indexa5200.zip)
> 
> (UPDATED to include bios) Sample Config file scan generated: https://paste.thec0de.com/?aa6f421bf38929f3#AhwdX2xDbApi8LLLDqKJPrTJTTovbRa5ZhFaDGJcrAkh
> 
> EDIT: Turns out you don't NEED the bios, but it seems to be 'better' (arguably) if you DO have it. Attaching it here (5200.rom) as zip. [5200.zip](https://github.com/linuxserver/emulatorjs/files/13881277/5200.zip)
> 
> Logo for Main also added (need to get video and a few other things) ![atari5200](https://private-user-images.githubusercontent.com/5171932/295329430-2aa270b5-2ff6-4def-84f9-193d91512361.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxMTI1MTEsIm5iZiI6MTcwNTExMjIxMSwicGF0aCI6Ii81MTcxOTMyLzI5NTMyOTQzMC0yYWEyNzBiNS0yZmY2LTRkZWYtODRmOS0xOTNkOTE1MTIzNjEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTNUMDIxNjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDI5YzVmMzRlOTEyMjUwYjQyZjg0YWIxNGYxZGE0OThhZTFjMTg1YWJmZGU4OGM5Y2M3YmY5MTE1ZTdmZTI3NyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.KzHHJXtfaxIQJ8Mlj3lIi340WuesXGFbOUbB_ou7gXg)

Hi, any chance to open a PR for my reference? I want to add js-dos and another core too and want to now the step-by-step. @thelamer maybe in the future add a step-by-step to add a new emulator, I want to test some.

**Comment by gr33k** [comment]
I am not sure how to do a PR for this project personally. I can upload the files with changes but I don't have anything syncing up with my own code to do more than share my mods (let alone a modified docker image).

A how to would be nice if possible! I'd like to get ScummVM and a few others working. @webysther - you mention Dosbox - there are a few emscripten dosbox builds out there (some with MT-32 kinda working - i.e. https://github.com/joncampbell123/dosbox-x).

**Comment by webysther** [comment]
> I am not sure how to do a PR for this project personally. I can upload the files with changes but I don't have anything syncing up with my own code to do more than share my mods (let alone a modified docker image).
> 
> A how to would be nice if possible! I'd like to get ScummVM (This repo is archived now but great info https://github.com/juj/emscripten-scummvm - I think we can just build it from the main repo now) and a few others working. @webysther - you mention Dosbox - there are a few emscripten dosbox builds out there (some with MT-32 kinda working - i.e. https://github.com/joncampbell123/dosbox-x).

DOS get pretty solid on web now, [archive.org have a emulator too](https://archive.org/details/softwarelibrary_msdos_games) and the [js-dos pretty stable now](https://github.com/caiiiycuk/js-dos), lots of games that my wife play are from DOS, normally I get the port for other platform but normally the port s*cks, will the a great to have DOS on the project.

**Comment by gr33k** [comment]
Atari5200 is working great but no mapped controls yet and I can't figure out why I can't access the Rom Management screen. The console shows an error despite that it scans, hashes, and builds the config files successfully. The only thing i can't do is try to download the assets :(
![Screenshot 2024-01-13 at 6 17 29 PM](https://github.com/linuxserver/emulatorjs/assets/5171932/c3c4c24c-d276-4829-bf23-e202e3295040)

**Comment by thelamer** [comment]
atari5200 support is added with https://github.com/linuxserver/emulatorjs/commit/fbcb869418816534d8424dfbd6a16039d18a84c7, this is in the latest image.
