### ISSUE TITLE
List games by release date or fixed

### ISSUE THREAD

**Issue by webysther** [linuxserver/emulatorjs#127]
Maybe need to collect the release date but for some game will be great order by release date. Some game change the name with "The" and put the game in another location to far way from the main list of game series, will be great to make the list of games fixed if release date are not a consideration.

**Comment by thelamer** [comment]
Everything is based on the name in the metadata, any additional metadata would need to be added and be a sort option for the frontend. In general my focus with the wheel was to be extremely performant on massive 1000+ lists or games. This would not only be a lot of work updating 10s of thousands of lines of metadata but it would also involve some heavy refactoring of the frontend. 
From a time sink standpoint I want to focus on the cores, performance, and browser compatibility outside of polishing metadata. So while this is feasible it is a lot to bite off.
