### ISSUE TITLE
Nintendo DS Hashes to update

### ISSUE THREAD

**Issue by gr33k** [linuxserver/emulatorjs#132]
Here are my Nintendo DS Hashes. The latest threaded version works pretty good, so I decided to set it all up. This isn't a complete collection list as.. well...I'm not a fan of every single oddball game they made on Nintendo DS. But it's still a pretty good size list.

https://paste.thec0de.com/?fc17180f2c261324#xXzijfe92D2kwjF99zzJBLn9JEwGQ31w2DuP2ofNJMn

🍻 Cheers! 🍻 

UPDATE: Also uploaded many logos and videos from screenscraper.fr - hope you can import those as well (Port 4001 open)

**Comment by thelamer** [comment]
I only see reference metadata in this paste (sha linking).

**Comment by gr33k** [comment]
Yes the link is only metadata - I was saying that I uploaded a lot of art logos and videos on my server. I hope that you will be able to pull it from there as I have port 4001 open :)

**Comment by thelamer** [comment]
without knowing the CIDs of those and having them linked in the metadata I have no way to update them in this repository.

**Comment by gr33k** [comment]
I see what you are saying - my apologies for the confusion!

Here is the updated NDS hashes with logo/video info as well:

https://paste.thec0de.com/?2520c1d853089e4f#HsZ9jyktkNZe7vCKFRdcjkNhHJqQ99Rr5CMYpiBfgEsn

That said - I understand what you need and will post more updates in the near future. I've updated all my SegaCD videos (for example) and filling in the holes for other consoles that are missing logo/videos.

**Comment by thelamer** [comment]
closing link https://github.com/linuxserver/emulatorjs/issues/134
