### ISSUE TITLE
[FEAT] Way to jump through rom list by letter/trigger

### ISSUE THREAD

**Issue by gr33k** [linuxserver/emulatorjs#133]
Some folks might have quite the large rom list added for some consoles/arcade (I have over 5000 for Arcade myself). This makes it extremely cumbersome to scroll through a long game list (heaven forbid you back out and you get back to the start of the list!). 

Could we make it possible so when we type a letter (or make a hotkey for this perhaps) to jump to that letter in the rom list that the games start with (similar to hyperspin)?

There is also ways to skip a few pages down by using the left/right shoulder/trigger buttons in mose similar Hyperspin wheel themes too.

So two pieces:
1) Jump to letter
2) Jump a few pages down via left/right trigger (or similar)

**Comment by thelamer** [comment]
page up and down on keyboard
right and left shoulder buttons on the controller
and on touch you hold and drag up or down

**Comment by gr33k** [comment]
Well now...I blame the fact that I use a laptop primarily lol.

That works - Thank you!
