### ISSUE TITLE
More Hash Updates (Video/Logo Updates included for many as well)

### ISSUE THREAD

**Issue by gr33k** [linuxserver/emulatorjs#134]
**Atari 7800**

I see there are 59 games that were ever released for the Atari 7800. I have uploaded the missing videos, so hopefully this is a full collection now on your server:

https://paste.thec0de.com/?da8cc4168ec9cfa9#A4XgX77tv39tPHtJoNs9yhyPa7Bif41R8miaB9KV4wCB

**Panasonic 3DO**

Many games and video updates - missing some adult games..maybe missing a few titles but pretty full set

https://paste.thec0de.com/?ba3ea4d5bcb315d7#8wWvJHEEDgMcrJTvuDAToGdJA71g2B15qrRV64VFSctU

**DOOM**

Minor Doom Update (Doom 1,2,Ultimate,Evilution):

https://paste.thec0de.com/?a67c8f44310424c2#G163JPAqGFCUf6a8md7a3PUSESsTvFTPbjy4eekfoWAG

**Gameboy Color**

Was missing Pokemon Yellow(!) Plus a few more updated videos/logos:

https://paste.thec0de.com/?dc9a9cf2028556bc#C3GRkpm4yWqiczDWTDBZzt3n8tw22c157V28iRsDZcdZ

**Sega CD**

Video/Logo Updates mainly:

https://paste.thec0de.com/?f4549122b4864a0f#4EYTCXGvGjjtB8MEjKWi3nGrTBmH5h4GXT4AouYW1ZEu

**Vectrex**

Minestorm 2 updated video/logo:

https://paste.thec0de.com/?a7d9c4734792fc50#CfVcEdjjYdg666w7LDerPhWE3rFZwUWZLozH5dKoE6bJ

**Jaguar**

Should be all released games now with video/logos:

https://paste.thec0de.com/?59d1a9a254287845#EbRChcnqmSP29Sy7mxnZqVKbsxD1uECRaaL9epXeWYfV

**Sega 32x**

Few more videos/logos:

https://paste.thec0de.com/?9517b32a4549ab03#7dLFhXg14LrULeXYhouzzg8cfUvMM5hLGuGf7EjnFhiy

**GameBoy Advanced**

Videos/Logos:

https://paste.thec0de.com/?0888d5eca141cd98#H1Sm1xLfxrWvVi2tUEUUNdPb7a7uMNpAfbwkvg98vpgh

**GameGear**

Videos/Logos:

https://paste.thec0de.com/?3fabb0b8a17ff3ee#5ytZBwVfqu5ysHNAYh3TkhHVMbiGahZmenziUZukZCGs

**Atari Lynx**

Minor Video/Logos added:

https://paste.thec0de.com/?5eb59cfb2012122c#82Dv44NTJjjBWo252p75GTnVvqGNpF4AqNuMq1NWJwMi

**Nintendo 64**

Minor Pokemon Stadium (1) video/logo:

https://paste.thec0de.com/?41541186e45e64ba#Dk9c7nN31nhbo6n1AwXXyT1uaBzY6mxo9WQgj534ExEt

**NES**

Minor Earthbound video/logo fixed:

https://paste.thec0de.com/?473599bd8450f7a9#3boAWcEZMbqMxnpP8uy5we3cdewkqbKXJwVxsD8XpFfA

**PC Engine**

Fixed 2 Japanese games missing videos (and 1 logo):

https://paste.thec0de.com/?204339e0633c4750#FBcTJyUk9DoLCeFukcSLFnWTnjaVRc1Zj5QibdWnpyE3

****

More to follow....I'll post them on this thread - still working on updating some more.

**Comment by gr33k** [comment]
Couldn't help but notice that some entries are flagged "Green" but are missing videos (they just have logos). Is there a way to flag these yellow perhaps? It would make it much easier for someone like me to find the entries which have missing items (it should be yellow if it's missing logo OR video I suppose). Currently, I have to scroll through the GUI to find ones that are missing videos (or click each game through the list and check if video is missing).

I also noticed that sometimes roms without art appear back in the game list (despite that I've click remove roms with no art). I'm not 100% certain what's causing this...be it restarting the docker container, or some other actions. I have to go through and click each system "remove roms with no art" again :(

**Comment by thelamer** [comment]
@gr33k I can't grab these CIDs, and I recall last time you had to re-upload. What I suspect is happening is you are upgrading the container and losing the `/data/.ipfs` directory in the process. 

What is the volume config on your container? 
If you are doing the rom directory mounts I changed that recently: 

**Mounting in existing rom directories Read Only can be achieved by using a special root path `/roms`, For example for NES:**

`-v /path/to/nes/roms:/roms/nes:ro`

**Comment by thelamer** [comment]
adding the paste from NDS to close it out: 
https://paste.thec0de.com/?2520c1d853089e4f#HsZ9jyktkNZe7vCKFRdcjkNhHJqQ99Rr5CMYpiBfgEsn

**Comment by gr33k** [comment]
Sorry @thelamer - I will repost all those when I have some time to go through and grab them all again...I just haven't had the time recently.

Here is my build script:
`#!/bin/bash
echo 'Building EmulatorJS'
echo 'Stopping EmulatorJS'
docker stop emulatorjs
echo 'Updating Image..'
docker pull lscr.io/linuxserver/emulatorjs:latest
docker rm emulatorjs
echo 'Building Image..'
docker create \
  --name=emulatorjs \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Los_Angeles \
  -p 3000:3000 \
  -p 88:80 \
  -p 4001:4001 `#optional` \
  -v /data/Containers/emulatorjs:/config \
  -v /data/Containers/emulatorjs:/data \
  -v /data/Consoles/MAME_emulatorjs:/data/arcade/roms \
  -v /data/Consoles/roms/Atari2600:/data/atari2600/roms \
  -v /data/Consoles/roms/Atari7800:/data/atari7800/roms \
  -v /data/Consoles/roms/Colecovision:/data/colecovision/roms \
  -v /data/Consoles/roms/Gameboy:/data/gb/roms \
  -v /data/Consoles/roms/GameboyAdvance:/data/gba/roms \
  -v /data/Consoles/roms/GameboyColor:/data/gbc/roms \
  -v /data/Consoles/roms/AtariJaguar:/data/jaguar/roms \
  -v /data/Consoles/roms/AtariLynx:/data/lynx/roms \
  -v /data/Consoles/roms/N64:/data/n64/roms \
  -v /data/Consoles/roms/NES:/data/nes/roms \
  -v /data/Consoles/ROMS/Panasonic3DO:/data/3do/roms \
  -v /data/Consoles/ROMS/Odyssey2:/data/odyssey2/roms \
  -v /data/Consoles/ROMS/Sega32X:/data/sega32x/roms \
  -v /data/Consoles/chd_segacd/CHD-SegaCD-NTSC:/data/segaCD/roms \
  -v /data/Consoles/ROMS/GameGear:/data/segaGG/roms \
  -v /data/Consoles/ROMS/SegaGenesis:/data/segaMD/roms \
  -v /data/Consoles/ROMS/SegaMaster:/data/segaMS/roms \
  -v /data/Consoles/ROMS/SegaSaturn/USA_Roms:/data/segaSaturn/roms \
  -v /data/Consoles/ROMS/SG1000:/data/segaSG/roms \
  -v /data/Consoles/ROMS/snes:/data/snes/roms \
  -v /data/Consoles/ROMS/VirtualBoy:/data/vb/roms \
  -v /data/Consoles/ROMS/GCEVectrex:/data/vectrex/roms \
  -v /data/Consoles/PSXISO/PSXISO_out:/data/psx/roms \
  -v /data/Consoles/roms/TurboGrafx16:/data/pce/roms \
  -v /data/Consoles/ROMS/WonderswanColor:/data/ws/roms \
  -v /data/Consoles/DOOM:/data/doom/roms \
  -v /data/Consoles/Microsoft_MSX:/data/msx/roms \
  -v /data/Consoles/Nintendo_DS_Collection/NintendoDS_Emulators/roms:/data/nds/roms \
  -v /data/Consoles/ROMS/Atari5200:/data/atari5200/roms \
  --restart unless-stopped \
  lscr.io/linuxserver/emulatorjs:latest
docker start emulatorjs
echo 'Done!'`

**Comment by thelamer** [comment]
Yeah checkout the readme in the docker-emulatorjs repo, you want to start using the /roms to method detailed there. That way stuff will survive upgrades. Need to swap out all the /data/Consoles mounts and make sure there are no rooms directories in the Containers data directories (there shouldn't be right now)

**Comment by gr33k** [comment]
Here is the repost - I set ro on all my mounts and will refrain either way from updating/restarting it until I see you have imported them ;) THANKS FOR ADDING ATARI5200 (Included it here)

3DO:
https://paste.thec0de.com/?a3c5d2ea620197a2#BgzdSMrZtrsqiBN5G7BZ1BZ5hAxxrhR6bagustwKWfeK

Arcade:
https://paste.thec0de.com/?357402b4e2a9ec02#JMMAf59ozHb1RbyawzxJEaMo3cCYbUnnqdy1Bfzwr5b

Atari2600:
https://paste.thec0de.com/?ce447e5a4fe1c78b#9ea8N6dvRHYfEaCDJoNhKqt4NoJs72cbNrvRdjgWcyjc

Atari5200:
https://paste.thec0de.com/?a0013d31d4e04684#3iB37vQQpPHPgcsTDXJva8n5bmNrLjuqEaVikEvx9zMm

Atari7800:
https://paste.thec0de.com/?885d4a31e789222d#5KY6kwxk9ArPkhTYCx3Mtqav2kGPM32uh41z98bgWJ99

Colecovision:
https://paste.thec0de.com/?9cb16023b205d357#2yUnQbxrmQEYELbKJWA2h23psQMjUxHU1rM2rPnDkePT

Doom:
https://paste.thec0de.com/?d1f6d1cdf735d87f#v1WGWYdpEhLe95UsQeP6u1iF4BL5GFTozYNxPbAUZRK

Gameboy:
https://paste.thec0de.com/?b66e5d5441d50bf9#4ctie7UdrbxvDAVLigshnCu394qDEA8Ki4XwyWbT2yTi

Gameboy Advanced:
https://paste.thec0de.com/?5bb35e089161d770#2Gm9Gz3bFDMcyWav3ZKr9LweVdjDL8ctouV5LH2wy11B

Gameboy Color:
https://paste.thec0de.com/?1a0fe3e8737bfc87#FXdq8ZJBZfcs84YkxoxeBWcbJmxHa1yeKmpswn9BxQZf

Jaguar:
https://paste.thec0de.com/?13232bc02cb373e2#3dQ118XTeunDg7k8yTin3BFnnurW7j15ESJkK67d3Hc9

Lynx:
https://paste.thec0de.com/?6f7054d12c7893fe#3u2yKM5NaFTvb1SsqQiscjZyjKm4p8VNkHT9739tAR1S

N64:
https://paste.thec0de.com/?3e2bd952720b0bd5#7BRfGnQ9gQjj9zySYeNMJx8WdEdtjemNRfo9QvTmV5q

NDS:
https://paste.thec0de.com/?b14e8a19b63e8469#TUoBms5CdaYneUphHNiYGA7RMSq1yrLN7nzcAwZLqxd

NES:
https://paste.thec0de.com/?7e9650682e62fbef#7b2n4APmWbSpgL7RFLMdTMt5bUm17x6G1KGhF9Vx9VY2

PCE:
https://paste.thec0de.com/?451bf6c46a1094db#8cW2uWPv9xb9YChDvZiYHpZhongNBtoJyinFWT9UYvVQ

PSX:
https://paste.thec0de.com/?db9258cd7189750b#97UJkYqs8B9TFFGNvCqUKCEHPNYDCfRGPzqaAPM8zy9o

32X:
https://paste.thec0de.com/?01cb9c1b887d031f#B5w41wNqc1TGbtoH7JggrwbhJzgmjwGm7C9Sizjaja61

SegaCD:
https://paste.thec0de.com/?e0ec045119ee97f6#CNZnWtB2UoK7S6Xnjq9y3Siq1FY8YRncEEepSdCYGoVe

SegaGG:
https://paste.thec0de.com/?ec027f7f1f45a411#Cr3mNXGdNPMKxfHEMcWZBJkLfRY66mXd76NSL9c5utDX

SegaMD:
https://paste.thec0de.com/?3299dea1e33bb9a0#A4sCActAn1Tb7Vi7rdY9mU5KtZp6Dyr1vt2YQhENR6aa

SegaSG:
https://paste.thec0de.com/?a5ea21d9ddd0f46a#A1BzhJduEKxrGhfQvSj6Sf8Get8yyhtBdJAm1PmKKiJY

SegaSaturn:
https://paste.thec0de.com/?a2b46647d9e0dce1#2UYxUWPiK1D9eZDUKnF1mKqmUUTiJ755wQxGTdmzQsdv

SNES:
https://paste.thec0de.com/?84d839895646eb84#GNKgaEkGEs1XjpCzivwEFa2Y4iDtuyqEYwygRxUngCpe

VB:
https://paste.thec0de.com/?55f4b8c6f1d71297#aHMTs8k8bPoH53BSoZ8f8n8tQGRyRpBHJfWAyGTj4su

Vectrex:
https://paste.thec0de.com/?3b40cca868f407de#9H7GhEvcKX55uiLdbD4r5dQ5kBTHo1bfbhPgSG33Lbf5

WonderSwan:
https://paste.thec0de.com/?a18d0a41c62469bd#QhBT1pAfvwtkT7kqibz9Xskmr3Jfq1muukkFPTfUqpQ

All I have so far :)

**Comment by thelamer** [comment]
I still cannot get any of these can you ensure at least one file can be pulled from a pub gateway IE
https://gateway.pinata.cloud/ipfs/QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD

**Comment by gr33k** [comment]
How can I test this?

I did a curl from the container to that URL and I got a response...
https://paste.thec0de.com/?0441445b78adaf13#8DwDkhzCYxb7rWP4X9RWQnTBEuWMeusa6JbJSsDUMCsr 

A wget says:
```
root@56bfb92c759e:/# wget https://gateway.pinata.cloud/ipfs/QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD
Connecting to gateway.pinata.cloud (172.64.154.225:443)
wget: server returned error: HTTP/1.1 429 Too Many Requests
```
Here is the netstat from the container:
```
root@56bfb92c759e:/# netstat
Active Internet connections (w/o servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       
tcp        0      0 56bfb92c759e:4001       47.113.117.144:4001     ESTABLISHED 
tcp        0      0 56bfb92c759e:4001       45.77.70.54.vultrusercontent.com:4001 ESTABLISHED 
tcp        0      0 56bfb92c759e:4001       213.159.196.136:46522   ESTABLISHED 
tcp        0      0 56bfb92c759e:4001       li1415-174.members.linode.com:4001 ESTABLISHED 
tcp        0      0 56bfb92c759e:4001       fin1.files.privex.io:4001 ESTABLISHED 
tcp        0      0 56bfb92c759e:3000       ::ffff:192.168.10.199:62417 ESTABLISHED 
```
A curl (all be it not the best example) also got a response "Project ID required" (expected):
```
root@56bfb92c759e:/# curl "https://ipfs.infura.io:5001/api/v0/add?pin=true"   -X POST -H "Content-Type: multipart/form-data"   -F "file=@\"/data/atari2600/backgrounds/default.png\""
project id required
```

**Comment by thelamer** [comment]
All of your ipfs files are essentially duplicated in `/data/Containers/emulatorjs/.ipfs` somehow it seems that folder got lost and has been regenerated since you went through and uploaded all your custom files.
I'll admit the logic to transition from the old scheme to the /roms symlinks is not perfect but you can shut the container down and just make them manually if need be this is all the container would do itself.
IE
```
docker stop emulators
cd /data/Containers/emulatorjs/arcade
rm -Rf roms 
ln -s /roms/arcade roms
```
Then the mount line in docker would be:
```
-v /data/Consoles/MAME_emulatorjs:/roms/arcade:ro
```

You also cannot use the same directory for /config and /data like that it should be 
```
-v /data/Containers/emulatorjs-config:/config
```
Or something else just not identical.

Now this does not solve the underlying problem the .ipfs directory was lost between a container upgrade or up/down so that data needs to be backfilled into the .ipfs directory.
Short of manually going through all the uploads again you can exec into the running container and run ipfs add IE:
```
docker exec -it --user 1000:1000 bash
export $HOME=/data
ipfs add /data/arcade/logos/*
ipfs add /data/arcade/videos/*
```
repeat for any systems you uploaded custom vid/logos for.

I recommend getting the directory mounts correct first then doing a backfill on the running container.
Once that is complete you will be able to confirm it worked by hitting the URL https://gateway.pinata.cloud/ipfs/QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD as this is one of your custom uploaded assets.

**Comment by gr33k** [comment]
I've not forgotten about this open issue...Just haven't had a chance to re-do all the folder structures yet - but I will!

**Comment by gr33k** [comment]
I have restructured the folders and the mounts appear to be working. I also moved the config folder and it had me re-download configs it seems (though it has all the games still appearing). I seem to have to add all roms to config to make them appear on the front end again. No biggie.

Here is my build script if you don't mind verifying that it's good now please:

```
docker create \
  --name=emulatorjs \
  -e PUID=1000 \
  -e PGID=1000 \
  -e TZ=America/Los_Angeles \
  -p 3000:3000 \
  -p 88:80 \
  -p 4001:4001 `#optional` \
  -v /data/Containers/emulatorjsconfig:/config \
  -v /data/Containers/emulatorjs:/data \
  -v /data/Consoles/MAME_emulatorjs:/roms/arcade:ro \
  -v /data/Consoles/roms/Atari2600:/roms/atari2600:ro \
  -v /data/Consoles/roms/Atari7800:/roms/atari7800:ro \
  -v /data/Consoles/roms/Colecovision:/roms/colecovision:ro \
  -v /data/Consoles/roms/Gameboy:/roms/gb:ro \
  -v /data/Consoles/roms/GameboyAdvance:/roms/gba:ro \
  -v /data/Consoles/roms/GameboyColor:/roms/gbc:ro \
  -v /data/Consoles/roms/AtariJaguar:/roms/jaguar:ro \
  -v /data/Consoles/roms/AtariLynx:/roms/lynx:ro \
  -v /data/Consoles/roms/N64:/roms/n64:ro \
  -v /data/Consoles/roms/NES:/roms/nes:ro \
  -v /data/Consoles/ROMS/Panasonic3DO:/roms/3do:ro \
  -v /data/Consoles/ROMS/Odyssey2:/roms/odyssey2:ro \
  -v /data/Consoles/ROMS/Sega32X:/roms/sega32x:ro \
  -v /data/Consoles/chd_segacd/CHD-SegaCD-NTSC:/roms/segaCD:ro \
  -v /data/Consoles/ROMS/GameGear:/roms/segaGG:ro \
  -v /data/Consoles/ROMS/SegaGenesis:/roms/segaMD:ro \
  -v /data/Consoles/ROMS/SegaMaster:/roms/segaMS:ro \
  -v /data/Consoles/ROMS/SegaSaturn/USA_Roms:/roms/segaSaturn:ro \
  -v /data/Consoles/ROMS/SG1000:/roms/segaSG:ro \
  -v /data/Consoles/ROMS/snes:/roms/snes:ro \
  -v /data/Consoles/ROMS/VirtualBoy:/roms/vb:ro \
  -v /data/Consoles/ROMS/GCEVectrex:/roms/vectrex:ro \
  -v /data/Consoles/PSXISO/PSXISO_out:/roms/psx:ro \
  -v /data/Consoles/roms/TurboGrafx16:/roms/pce:ro \
  -v /data/Consoles/ROMS/WonderswanColor:/roms/ws:ro \
  -v /data/Consoles/DOOM:/roms/doom:ro \
  -v /data/Consoles/Microsoft_MSX:/roms/msx:ro \
  -v /data/Consoles/Nintendo_DS_Collection/NintendoDS_Emulators/roms:/roms/nds:ro \
  -v /data/Consoles/ROMS/Atari5200:/roms/atari5200:ro \
  --restart unless-stopped \
  lscr.io/linuxserver/emulatorjs:latest
docker start emulatorjs
```
When I try the next step to fix IPFS I get an error on the first two commands. Is this something to worry about or can I safely ignore it?

```
docker exec -it --user 1000:1000 emulatorjs bash
bash: /root/.bashrc: Permission denied
abc@57d3d7a216a8:/$ export $HOME=/data
bash: export: `/root=/data': not a valid identifier
```
I wanted to make sure this is ok before I start the arduous process of fixing IPFS :)

Thank you!

**Comment by thelamer** [comment]
My bad 

`export HOME=/data`

**Comment by gr33k** [comment]
OK, I did all the ipfs adding and it seems to have completed with no errors. I restarted the container. However, when I go to the URL you provided I get:

`The request timed out searching for a file on the non-pinata IPFS network. - ERR_ID:00016`

Does it take a while before it syncs up perhaps?

**Comment by thelamer** [comment]
No it is pretty instant, that cid in particular was from your 3do metadata specifically a logo `QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD` it might simply not be on your machine if you did an ipfs add. 

You can pull from your local node to see if it has it: 
```
docker exec -it --user 1000:1000 emulatorjs bash
cd /config
export HOME=/data
ipfs get QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD
```

If not, all the metadata you previously posted might not be valid anymore and things might have gotten mucked up in the migration process.

**Comment by gr33k** [comment]
Hmm it's there - it's the logo from Captain Quazar.

```
docker exec -it --user 1000:1000 emulatorjs bash
abc@e21b9c0228eb:/$ cd /config
abc@e21b9c0228eb:/config$ export HOME=/data
abc@e21b9c0228eb:/config$ ipfs get QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD
Saving file(s) to QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD
 60.15 KiB / 60.15 KiB [===================================================================================================] 100.00% 0s
abc@e21b9c0228eb:/config$ ls -l
total 1164
-rw-rw-rw-+ 1 abc users  11015 Feb 15 08:39 3do.json
-rw-------+ 1 abc users  61593 Feb 17 15:34 QmdojTsd6fdxZeAiCTSLnfKRGPx7xoddfhBAXp4yAYvuhD
```
I did the 3do ipfs add for 3do for both logo and videos.

**Comment by thelamer** [comment]
Well that narrows it down, can you ensure 4001 is piped out to the world ?
If your node knows about it and is communicating with other nodes it should be able to be grabbed through any gateway.

**Comment by gr33k** [comment]
Yep it's open - I scan TCP 4001 from my VPS and it shows open
➜  ~ nmap <mydomain> -p 4001

Starting Nmap 7.60 ( https://nmap.org ) at 2024-02-17 23:41 UTC
Nmap scan report for retro.thec0de.com (47.151.186.46)
Host is up (0.013s latency).

PORT     STATE SERVICE
4001/tcp open  newoak

**Comment by gr33k** [comment]
Ok - So I noticed you added Neo Geo Pocket (Thank you!) - I'm not done uploading all of the videos and logos there yet - but I did notice they appear on the site that you listed - for example:

https://gateway.pinata.cloud/ipfs/QmSx3a5tPuAib2weSmhCqPTVcKYtjU8qTkAdQxB7ab77SH

NeoGeo Pocket:
https://paste.thec0de.com/?d9f4dfce0075bb49#Eh5mupTQ9tU8aQ11MXQ3HsRt2uxpogDqumVf9Btdt4x2

**Comment by gr33k** [comment]
Not sure if you saw @thelamer the new stuff I uploaded made it to your server, but the old stuff still doesn't appear to have. If you have any ideas - happy to try them.

**Comment by gr33k** [comment]
Hmm - I was checking on the thread for an update and decided to click the links again to see if they are working...not only are they still not working, but the ones that I posted earlier saying they were working are NOT working for me anymore. Perhaps there is an issue retaining the files on the server side? Not sure why it worked before but not anymore :(

**Comment by thelamer** [comment]
Yes I noticed that too and honestly have no idea what is going on. Even if things were not being pinned your node should hold the file for 90 days and communicate to the network. Also I know you have contacted the seed server as a peer and I cannot ingest them from there. 
I don't want to totally give up but in general if you are happy with your setup isn't that what matters?

**Comment by gr33k** [comment]
I totally agree. I just wanted to share the work - but if it's too crazy to be worth the effort...it's ok. I am definitely happy with my setup and LOVE this project man!

Thank you for all your hard work 🍻
