### ISSUE TITLE
Custom Gameboy Advance touch layout

### ISSUE THREAD

**Issue by 8bitDesigner** [linuxserver/emulatorjs#135]
Hi there, and thanks for putting together this very cool version of EmulatorJS! I love my old-school GBA, and I'd love to add a cleaner version of the touchpad layout, and looking at [touchpad.js](https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/touchpad.js) it seems like an easy enough fix.

If I were to open up a PR for this change, is there any JS hijinks I need to go through (Webpack or similar build step), or does this project use vanilla JS?

**Comment by thelamer** [comment]
No it all plain and the minified external deps are all stored in repo. 
If you make a new layout make sure to have it get detected here as well: 
https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/index.js#L195-L202
