### ISSUE TITLE
changing default keyboard controls?

### ISSUE THREAD

**Issue by pine-serpent** [linuxserver/emulatorjs#136]
default the arrows are directions, z is b, x is a...
i know I can change controls in the f1 retroarch menu but how can I change them so they persist even after wiping cache/cookies in my browser? thank you!

**Comment by thelamer** [comment]
The code is here that sets the default file if it does not exists:
https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/libretro.js#L6-L8

You can also change the default profile file in the docker image: 

https://github.com/linuxserver/docker-emulatorjs/blob/master/root/etc/s6-overlay/s6-rc.d/init-emulatorjs-config/run#L29-L35

But that one is not automated it is only pulled when the user manually clicks pull default profile in the frontend. 

I have no plans to implement a server owner setting a default config, the idea is that it is the base settings retroarch uses for every client and they set it up how they want in their client space.

**Comment by pine-serpent** [comment]
thank you for the assistance ask your work!
