### ISSUE TITLE
enhancement: On-Screen Overlay (Bezels)

### ISSUE THREAD

**Issue by 60plus** [linuxserver/emulatorjs#14]
Is adding On-Screen Overlayare (Bezels) are planned in any update ?

I did try to expose other folder then /data to copy them in but no luck. Overlayare  folser is invisible in retroarch.

**Comment by thelamer** [comment]
The overlays for stuff like this is functional, but I pulled them out of the frontend files and compiled code because input based overlays are not functional. Helped cut the frontend zip that is pulled for every launch down from like a couple hundred megs to 3.3 . 
Might revisit down the line, but for right now I think it causes confusion as many people use the overlays for stuff like mobile support.

**Comment by 60plus** [comment]
Thanks for answer.It would be nice because these black bars are not very aesthetic.So as not to increase the size of frontend could you add a way to add them yourself ? in this way, only interested people will add them.Sorry for my broken english is not my native language

**Comment by thelamer** [comment]
Not easily unfortunately, you would need to build the cores from source. 
Relevant code line:
https://github.com/thelamer/retrostash/blob/master/RetroArch/Makefile.emscripten#L20
Then modify the contents of the `/emulatorjs/data/frontend.zip` file to include the overlays you wanted. 
I will possibly look into some type of implementation in the future, but honestly for the vast majority of use cases the emphasis for web is keeping things as lean as possible. These add a performance hit when enabled and as mentioned earlier are downloaded on every game load.
As is, the sandbox these emulators live in is a single CPU thread on the client machine's browser with an unknown GPU configuration for webgl, thus why performance considerations are taken. What may work well for you on your desktop PC might seriously slow down someone on an old phone for example.

**Comment by thelamer** [comment]
The latest version includes a web based file manager for the retroarch stateful storage, when they (libretro) cut their next release I will rebuild the cores to point the shader and overlay directories to this stateful storage and users will be able to upload/manage their own shader collection.

**Comment by thelamer** [comment]
New release https://github.com/libretro/RetroArch/releases/tag/v1.10.0 , I will update all the cores and the next cut release will have overlay support built back in.

**Comment by thelamer** [comment]
Overlays can be loaded in the latest release 1.6.4. 
There are no defaults so you will need to upload them from the file browser interface.
