### ISSUE TITLE
Unidentified Megadrive / Genesis ROMs

### ISSUE THREAD

**Issue by annomatik** [linuxserver/emulatorjs#141]
Hi! I can't run the following Megadrive / Genesis ROMs as they are marked as unidentified.

![image](https://github.com/linuxserver/emulatorjs/assets/28311452/d7b787b2-c0dd-4a54-8231-d8ae1948980d)

**Comment by thelamer** [comment]
click on them

**Comment by thelamer** [comment]
There is a manual identification for this reason. Does that same zip file work on a local install of retroarch?

**Comment by annomatik** [comment]
Haven't tried it. It works with a local copy of "Fusion", a genesis emulator. Unfortunatelly, with the manual identification, I still have to select an item from a list. In that list, the game does not show up (Homebrew).

**Comment by thelamer** [comment]
Can you put them in zip files ?

**Comment by annomatik** [comment]
Yes, I can. But its in .smd, like all the other ones that are working -- why shouldn't this one work as smd as well? Apparently, there is a list of pre-defined games. This game is not in it. Can I add to that list? Or can I tell the system to use a game that's not in that list?
