### ISSUE TITLE
Error: fs-repo requires migration

### ISSUE THREAD

**Issue by Carontes** [linuxserver/emulatorjs#142]
Hello, in the terminal I receive this error message even if everything is working fine

`emulatorjs  | Please get fs-repo-migrations from https://dist.ipfs.tech
emulatorjs  | 
emulatorjs  | Initializing daemon...
emulatorjs  | Kubo version: 0.24.0
emulatorjs  | Repo version: 15
emulatorjs  | System version: arm64/linux
emulatorjs  | Golang version: go1.21.8
emulatorjs  | Found outdated fs-repo, migrations need to be run.
emulatorjs  | Run migrations now? [y/N] Not running migrations of fs-repo now.
emulatorjs  | Please get fs-repo-migrations from https://dist.ipfs.tech
emulatorjs  | 
emulatorjs  | Error: fs-repo requires migration
emulatorjs exited with code 0`

Do I have to install fs-repo-migrations? How to install it? Thank you

**Comment by thelamer** [comment]
No we handle this here with this hook, try execing into the container and run it manually 
https://github.com/linuxserver/docker-emulatorjs/blob/master/root/etc/s6-overlay/s6-rc.d/init-emulatorjs-config/run#L14

**Comment by Carontes** [comment]
I tried to execute that line in the container console and this is the result

`root@8a31a6fe1fc0:/# HOME=/data s6-setuidgid abc /usr/bin/fs-repo-migrations -y -to 15
Found fs-repo version 11 at /data/.ipfs
2024/04/04 19:25:03 Looking for suitable migration binaries.
2024/04/04 19:25:03 Running migration fs-repo-11-to-12 ...
2024/04/04 19:25:03   => Running: /usr/bin/fs-repo-11-to-12 -path=/data/.ipfs -verbose=true
ipfs migration:  migration fs-repo-11-to-12 failed: signal: segmentation fault`

Maybe I'm doing something wrong

**Comment by thelamer** [comment]
It might just segfault on aarch64, going from 11 to 15 is not something I personally tested on aarch64. 

If this was my machine I would just stop the container remove the `/data/.ipfs` directory (if you have not uploaded any custom assets yourself) and start the container. 

This will init a version 15 empty ipfs repo, When you click any of the download actions it will need to ingest from remotes again to backfill but it will get you running again.
