### ISSUE TITLE
Any way to change touchpad controls?

### ISSUE THREAD

**Issue by CollinKasbergen** [linuxserver/emulatorjs#143]
I would like to use a d pad while emulating GBA,GBC and GB games rather than a joystick. I tried changing the overlay in the Retroarch menu but then it shows both the added overlay as well as the emulatorjs touchpad. 

Update: Just found out there is a drop down menu with touchpad options in the file browser. Sadly no option for a d-pad based layout

**Comment by thelamer** [comment]
We should not load the touchpad if a controller is detected that check is here https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/index.js#L186
I test controllers on iPad and personally use a kishi.
What is your setup?

**Comment by CollinKasbergen** [comment]
I mean the touchpad controls overlaying when playing on a mobile device without a controller

**Comment by thelamer** [comment]
There is no touch dpad, you can put 4 buttons there but trust me it is terrible.
In general touch controls are terrible, I welcome any help though.

**Comment by CollinKasbergen** [comment]
Think your right, got d-pad controls out of the box with [gaseous](https://github.com/gaseous-project/gaseous-server) and it wasn't much better then the joystick in emulatorjs. Ordered a Miyoo Mini Plus to sync my roms library to instead rather then all this web based stuff. Really cool project tho if you like to play with an external controller, that it works on the xbox browser just amazed me.
