### ISSUE TITLE
Has anyone been able to add on screen buttons for iOS/Safari ?

### ISSUE THREAD

**Issue by FadingArabChristians** [linuxserver/emulatorjs#15]
I can get my roms to play on iOS/Safari but I can not input any controls/buttons. I cant pull up a menu either to attempt to add onscreen controls. Thanks

**Comment by thelamer** [comment]
There are no onscreen controls. I made a couple iterations but they were awful and really only useful for turn based stuff. The baked in overlay support in RetroArch does not work with the emscripten builds and I lack the know how to fix it, that is where I focused my effort vs a joystick nipple and a couple buttons. You need to hook up a controller, I would recommend a modern Xbox controller or the Razer Kishi, but any Bluetooth controller should work.

**Comment by FadingArabChristians** [comment]
I'll look into that, thank you!
