### ISSUE TITLE
SHA Error while scanning multiwad files

### ISSUE THREAD

**Issue by nad22** [linuxserver/emulatorjs#150]
Hi!
I just created a multiwad file (zip file with doom2.wad and a custom gnndoom.wad file) like described on the page in the backend. While i scan for new files in doom i get this error: 

Scan exited with code: 1
sha1sum: '/data/hashes//doom/roms//tmp/gnndoom.*': No such file or directory
hashing gnndoom.multiwad
unzipping gnndoom.multiwad

**Comment by thelamer** [comment]
Sorry for the delay I have not been on top of these issues.

You need to have at least one file named after the multiwad inside the zip. So in this case `gnndoom.zip` needs gnndoom.wad inside of the zip.
