### ISSUE TITLE
Change n64 core to prevent crashes

### ISSUE THREAD

**Issue by mpclepto** [linuxserver/emulatorjs#151]
Playing a game like mario tennis on n64 crashes usually within 5 minutes. Is it possible to change cores to run this under something like mupen64? I'm seeing reports elsewhere on the internet that this runs the game smoothly.

I've seen this issue with both Brave browser and Edge (both have all adblockers turned off and such).

My brother and I love the project, thanks for all the hard work! I'm just hoping to kick his but around the court!

**Comment by thelamer** [comment]
That is not really how this works, the only emscripten core that works is one toadking cooked up and other devs polished over the years: 
https://github.com/libretro/mupen64plus-libretro-nx/pull/514
