### ISSUE TITLE
Add support for Commodore systems (VICE core)

### ISSUE THREAD

**Issue by aeonoea** [linuxserver/emulatorjs#152]
Hi all,

In a February release the devs of EmulatorJS added the VICE core for various systems such as commdore64 etc., see [release notes](https://github.com/EmulatorJS/EmulatorJS/releases/tag/v4.0.10)

Now as of latest release of this docker container there seems to be no reference to the vice core or commodore systems. 

I noticed that the latest release is from March. Is it possible the February update has not made it into this fork yet? And would you consider updating the container to add support for the VICE core?

#54

**Comment by thelamer** [comment]
I went through and tested VICE when this project first kicked off, unlike MSX it is not clear to the user regarding how to control most games and gamepad support is flakey, in most cases hard requiring a keyboard. 

While I understand you have people that are very familiar with this emulator you have like 30 file formats to support, a whole list of bios variations, and different hardware revision modes. It is too much of a support nightmare and it was specifically left out of the codebase.
