### ISSUE TITLE
Rom Mangement unable to select games with 2 apostrophes in title

### ISSUE THREAD

**Issue by gr33k** [linuxserver/emulatorjs#153]
Hi there,

This issue has existed on all builds as far as I'm aware and is affecting the latest version. 

Any games with two ' (apostrophes) in them will cause an error in the web browser console and not let you select them to do anything edit/delete. Example titles:

Disney's 101 Dalmatians II - Patch's London Adventure (USA).chd
Freestyle Boardin' '99 (USA).chd

Chrome Console error when selecting any title with two apostrophes in there:

`Uncaught SyntaxError: missing ) after argument list`

Workaround: Rename the rom and remove the ' - annoying thing is you must do a full rescan to have it removed it seems (for my PSX collection over 1400 roms and it takes hours).

Hopefully this is an easy fix 😄 Love the project - looking forward to more emulators in the future 🍺

**Comment by gr33k** [comment]
@thelamer - should we be posting in this github still or in the new one at https://github.com/linuxserver/docker-emulatorjs ?
I have some custom metadata I wanted to share soon and want to post it in the right github (p.s. this github is still what is linked in the rom management web gui)

**Comment by thelamer** [comment]
So this was fixed and I did not mark the release properly it is in the codebase now https://github.com/linuxserver/emulatorjs/commit/b623e88332dfcc1d19d3e9a9f4771bd8a27cb80a
