### ISSUE TITLE
PSX doesn’t work.

### ISSUE THREAD

**Issue by EmperorsLoungeVPN** [linuxserver/emulatorjs#16]
Issue with the core used. I tried the other core provided directly with RetroArch and seems to work but not on the in browser one due to PSX Beetle. Also maybe a way to exclude .cue file scans when scanning for the game. More over getting rid of the .cue is not a supported game file.

**Comment by thelamer** [comment]
Use chdman to convert to chd is the only recommendation I can make. (This is documented heavily on the landing page along with multi disc support) Compress down your collection.
The only effort this program makes is to pull down a single bin and cue file, multi bins won't work.
In general when doing web stuff it is hard to automate the scanning and proper downloading of the files universally, having a single "rom" file helps immensely.
Not to mention the memory consumption as these files are stored in memory when downloaded.

**Comment by thelamer** [comment]
Ref docs:
https://retropie.org.uk/docs/CHD-files/
chdman is included in this image, so you can exec in to run a batch convert if you want.

**Comment by 60plus** [comment]
@EmperorsLoungeVPN PSX work perfect you need roms i CHD format. bin,cue sometimes work ISO dont work.

**Comment by EmperorsLoungeVPN** [comment]
Try single bin and cue files and seems the emulator doesn’t even load

**Comment by thelamer** [comment]
I am not going to implement logic to parse cue files as is for web loading. The only effort made currently is to look for GAME.bin if GAME.cue exists and download it also. 
Again I recommend using chd format if you want to use the web based PSX emulator.

**Comment by EmperorsLoungeVPN** [comment]
Already got it thanks. Working great. Will load my 1000 plus collection in now
