### ISSUE TITLE
[Feature Request] Add Quick jump alphabet to the rom selection screens. 

### ISSUE THREAD

**Issue by diskkonnected** [linuxserver/emulatorjs#18]
Would love to see a quick jump alphabet next to the rom selection. Right now if I want to play super mario brothers it takes forever to scroll to the S's. I use this on my tablet and the ability to do that would be game changing... no pun intended ;)

**Comment by thelamer** [comment]
The pan in touch mode is pretty quick, you just hold and drag up or down and release to stop. When using a keyboard you can also vastly increase the velocity by holding right while pressing up or down. 
I do want to make more navigation options though eventually, but right now concentrating on getting emulators running better on Xbox and safari for device compatibility.

**Comment by diskkonnected** [comment]
Sounds good :) Thank you for all your work on this.

**Comment by SerinitySW** [comment]
I would also love to see this, or even better a search feature. No rush though, love the project.

**Comment by thelamer** [comment]
This has been implemented in 1.6.2
PageDown/PageUp on keyboard
L1/R1 on gamepad
