### ISSUE TITLE
[Feature Req] adding our own libretro cfg files for defaults/overrides

### ISSUE THREAD

**Issue by ponchohoncho** [linuxserver/emulatorjs#19]
I love this project! It's seriously incredible.

libretro has a keyboard retropad mapping that uses arrow keys and z, x, a, s, q, w as the main buttons. I'd love to be able to specify a new default to use wasd and another set of keys for the buttons. Rather than changing this in every core in every browser I use, I'd love to be able to create a config, or export a core cfg override, and be able to use it with the cores in emulatorjs. In addition to changing key mappings, it would be possible to do things like set scanline filters, etc, as defaults for your self-hosted arcade.

Do you think this would be possible?

**Comment by thelamer** [comment]
In the latest version there is now a file explorer icon in the top left of the interface, this allows you to manage the browser storage and download/upload full backups. From here you can download your setup configs and load them into any other device.

**Comment by ponchohoncho** [comment]
That is a very helpful feature. I was also hoping to be able to set defaults, or perhaps upload a backup to be used as the default settings tat are pushed to all users, so that other users could use a different set of keymaps/overrrides without needing to upload/restore and do a whole dance.
