### ISSUE TITLE
Confusion

### ISSUE THREAD

**Issue by ethanaobrien** [linuxserver/emulatorjs#24]
Could you add a note in the readme or somewhere in the software stating that this project and my emulatorjs project are not the same. I've had several people open an issue asking for a feature that already exists just to find that they use this project.
It would also be helpful if you could slightly change the name of the project. (My project did come first)
Suggestion: Something like `emulator-docker` or something like that

Examples: [#43](https://github.com/ethanaobrien/emulatorjs/issues/43), [#50](https://github.com/ethanaobrien/emulatorjs/issues/50), [#83](https://github.com/ethanaobrien/emulatorjs/issues/83), [#87](https://github.com/ethanaobrien/emulatorjs/issues/87), [#110](https://github.com/ethanaobrien/emulatorjs/issues/110)

**Comment by ethanaobrien** [comment]
@thelamer Thank you for the info. I understand. I think the name fits the project. Would you mind adding a note in the UI saying to open an issue in this repository

Also, which repository do you use to host the source for the emulators?

**Comment by thelamer** [comment]
Yeah on the next release I cut I'll add link on the landing. 
https://github.com/thelamer/retrostash is the full current source for retroarch cores more notes here: https://github.com/linuxserver/libretrojs . 

Also while I have your ear the wasm from https://www.emulatorjs.com/ is crazy out of date. For 8 and some 16 bit it does not make a huge difference, but like for example arcade/snes/psx emulation is night and day using retroarch cores. 
I know you were following the thread on webretro but the multi threaded for DS and Saturn is seriously impressive turning completely unplayable to full speed:

https://user-images.githubusercontent.com/1852688/150008334-7c1d8711-2ba9-44be-8e4f-5173ca18d577.mp4

When it comes to arcade titles using modern mame-2003 builds opens a new world of compatible games: 

https://user-images.githubusercontent.com/1852688/150010301-ab3bab72-d93c-4872-a89d-a332696f40b8.mp4

Also in general Digging through the code I think (actually pretty sure at this point) https://www.emulatorjs.com/ is modified code from very old builds of https://neptunjs.xyz/ I am pretty sure the person hosting emulatorjs does not even have access to the source code. But in the end all of this is based on retroarch code with their web UI stuff bolted on top. At least with https://neptunjs.xyz/ they are the actual devs and are continuing to port over retroarch cores. Just bringing this up as it seems like you may be deobfuscating someone else's closed source deobfuscation effort.

**Comment by ethanaobrien** [comment]
Thank you, I'll take a look!

**Comment by thelamer** [comment]
I see you have been digging into the netplay stuff. That is really the only feature missing from the Retroarch cores. 
If you are interested in building cores and starting to tinker with the code I have some more docs here: 
https://github.com/thelamer/RetroArch/tree/emscripten-tweaks/pkg/emscripten

It should be possible to directly interface the current baked in netplay support in Retroarch with a websocket js addon with bindings, like is done with stuff like the audio https://github.com/libretro/RetroArch/blob/master/emscripten/library_rwebaudio.js . 

Just in general owning the code and building your own stuff opens it up to you learning and implementing your own features vs trying to adapt something without collaboration and inside of some one else's walled garden. 
I recall talking to you a while ago about the source and build logic for stuff, and with this it is all there with comments, documentation, and a big community of developers. If you have any questions about getting a full loop dev setup to start playing with these cores I am here to help.

**Comment by ethanaobrien** [comment]
@thelamer I really like the frontend of the emulatorjs project, I think It would be cool if we could update the core files so we wouldnt need to really re-write any of the UI stuff. What do you think?

**Comment by thelamer** [comment]
A couple buttons on a screen is pretty low hanging fruit compared to exporting and linking up the functions in the emulator.
The advantage with the RetroArch UI is everyone knows it, it is maintained externally, and you have far far more fine grain options.
But it is completely possible to rebuild and put whatever point and click buttons you want rendered over the canvas. 
For example if you wanted to replicate a save button you would call the exported function `Module._cmd_savefiles();` from an onclick event in on your custom button, you want to save the resulting file you can wrap that in a function that after calling savefiles accesses the FS window object (emscripten file system) and loads the file to a blob for download.
There is more on interacting with the indexdb filesystem in the file browser I built out https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/filebrowser.js https://github.com/linuxserver/emulatorjs/blob/master/frontend/filebrowser.html
You can swap the RetroArch var in it to play around with the storage for emulatorjs. (Check application storage tab in your browser console to see the indexdb names)

So that is one function of the UI, you need exported functions for everything else like picking a shader or changing the controller mapping. It's not a huge burden but you would be forking off and maintaining code that is allready there and functional with the RetroArch frontend menu.

**Comment by ethanaobrien** [comment]
@thelamer 
Thank you for all the info. I'm going to ask some questions an I'm sorry if they seem like really easy and plain, I really only know JavaScript so I'll be learning as I go.
1. How would I make and export a function?
2. Could you tell me where the keypress event functions are in the retroarch code

I'm sorry, I just really don't understand C yet.

I have a list here or things to do: https://github.com/ethanaobrien/emulatorjs/issues/94

**Comment by thelamer** [comment]
Ok so your exported functions are here: 

https://github.com/libretro/RetroArch/blob/master/Makefile.emscripten#L67

So in this example the savefiles links back to this: 
https://github.com/libretro/RetroArch/blob/682bbab233ab1612eb69abf36ac9e0bbcbbfc1a1/frontend/drivers/platform_emscripten.c#L53-L56

Which links to: 
https://github.com/libretro/RetroArch/blob/311fec15d9db10ab14c879e898a8205dd37f827c/retroarch.c#L1486

And so on. 

As far as keypress those are translated here: 

https://github.com/libretro/RetroArch/blob/1ef78d3e3d8e8463790b1fb527510be51a38793a/input/drivers/rwebinput_input.c

But if you mean how do I press keys from javascript I guess I would need to know what you are trying to trigger to answer that.

**Comment by ethanaobrien** [comment]
Thank you, I'll take a look when I get the chance.

>But if you mean how do I press keys from javascript I guess I would need to know what you are trying to trigger to answer that.

I'd like to have each button tied to a keycode, and then when the user presses a key it is sent through the mapping and then sent to the emulator, having the mapping handled via javascript, not retroarch.

Also one more question. Is there a restart function somewhere I can use?

Thank you for your help!

**Comment by thelamer** [comment]
I think you may still be approaching this as man in the middle attacking the code like you don't have the ability to modify it to suite your needs. I am not technically capable enough to explain the code process of achieving everything you want to do if I was I would be rewriting and participating more heavily in the upstream project, but I think you should understand some fundamental stuff. 
Stuff like Neptunjs and emulatorjs while using libretro cores are likely using very little of the Retroarch frontend outside of referencing it for examples of how to achieve things. There are two parts here at play the cores and the frontend itself that gives the user a gui to adjust options: 
https://docs.libretro.com/development/libretro-overview/

So you build a core and then wrap that core with your fronted to interact with it and send commands via the libretro api. So you are talking about Calling C functions from javascript: 
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html
https://emscripten.org/docs/porting/connecting_cpp_and_javascript/Interacting-with-code.html#calling-compiled-c-functions-from-javascript-using-ccall-cwrap
Also look at `--js-library` file additions. 

What I am saying is you would not approach this as "how can I hack a way into tricking the existing code with man in the middle keypress function wrapper?" you would set the button mappings in javascript and then send those button mappings to the libretro api either individually or generate a mapping file and call input_remapping to load that file after you have exposed this to javascript as an exported function. 

For reset, the code you are looking for in the retroarch frontend is `RARCH_RESET` I believe. That is not currently exported as it exists in their frontend menu. 

I cannot write examples for you, I do not have that knowledge, but there is a large community for Retroarch development, I would recommend reaching out to them on discord or something. Not for overarching code on all fronts, but concentrated on single actions like "how could I achieve having a javascript button on a webpage call the reset action on an emscripten core?".

**Comment by ethanaobrien** [comment]
@thelamer Thank you. I have several ideas and plans for what I can do, thank you. Would you like me to inform you when the beta is ready?

**Comment by thelamer** [comment]
Yeah for sure, don't forget to reference: 
https://github.com/linuxserver/emulatorjs/blob/master/frontend/js/libretro.js
and:
https://github.com/libretro/RetroArch/blob/master/pkg/emscripten/libretro/libretro.js
For logic how to initialize the FS and load everything up.

**Comment by ethanaobrien** [comment]
Hey, @thelamer 
I learned how they called the functions so I didnt have to really re-write any javascript

Although, I do need some help. There seems to be problems with the canvas aspect ratio and resize. It cant find the canvas until I set the id of the element to `canvas` and if I set it before I `callMain` it won't render at all. 

When I do get the game to render, it is really fuzzy until I enter and then exit fullscreen. Do you have any ideas?


Only `nes` uses beta right now (if you've used the emulator before, you need to clear your cookies)
(Sorry, it wouldnt let me upload to github for some reason)
beta: https://drive.google.com/file/d/11_DryQmXamb3v9sR6mxZWwXXIH9PLQh6/view?usp=sharing

**Comment by thelamer** [comment]
`Module.setCanvasSize(width,height)` is what you are looking for. Reference the code in libretro.js to fire window resize events.

**Comment by ethanaobrien** [comment]
@thelamer 

>It cant find the canvas until I set the id of the element to canvas and if I set it before I callMain it won't render at all.

Do you happen to know why this happens? I have to manually put a try and catch in the file to make it work

**Comment by thelamer** [comment]
The canvas link is set on load in the Module settings object. It is how the wasm knows what to render to. So if you have to reorder that for any reason you just need to remember before the files are loaded it needs to be set. You can set it and hide the div if you are trying to show something else.

**Comment by ethanaobrien** [comment]
@thelamer Just thought I'd let you know. I have the boot process clean and working now! As you said much faster (and uses 1/10% of cpu compared to before) The only button I have working so far is the reset button, but it is progress!

beta: https://drive.google.com/file/d/11_DryQmXamb3v9sR6mxZWwXXIH9PLQh6/view?usp=sharing

**Comment by thelamer** [comment]
I see the core loading in the console, but I get a black canvas. You sure this is the working code?

**Comment by ethanaobrien** [comment]
It was when I checked yesterday. Something seems to have broken. (not working for me anymore either)

Are there any errors in the console?

**Comment by ethanaobrien** [comment]
@thelamer Do you know where in the code it actually draws (or renders or whatever you want to call it) onto the canvas? I think there's some sort of thing.

I think the problem could also be [here](https://github.com/libretro/RetroArch/blob/1ef78d3e3d8e8463790b1fb527510be51a38793a/input/drivers/rwebinput_input.c#L292) with the event listeners or [here](https://github.com/libretro/RetroArch/blob/682bbab233ab1612eb69abf36ac9e0bbcbbfc1a1/frontend/drivers/platform_emscripten.c#L165). What do you think?

**Comment by thelamer** [comment]
Just a heads up I have real life stuff to do for a bit along with my focus shifting off game emulation back to another project I have been running for web based desktop app containers. I can answer questions if I know them but won't be digging too deep into code for at least a couple weeks. As far as I understand it though the canvas linking and rendering is mostly handled by the Emscripten SDK: 
https://emscripten.org/docs/api_reference/html5.h.html
With the retroarch cores they leverage a bit of OpenGL ES in the frontend and menu rendering on top of that stack.

**Comment by ethanaobrien** [comment]
@thelamer Just thought I'd let you know. It is now booting cleanly. I found that I never called the `Module.resumeMainLoop` function and when I called that and called `Module.setCanvasSize(800, 600)` it successfully fits in the frame and works perfectly! The only button I have working so far is the reset button. Keymaps dont work yet.

beta: https://drive.google.com/file/d/11_DryQmXamb3v9sR6mxZWwXXIH9PLQh6/view?usp=sharing

**Comment by ethanaobrien** [comment]
Hey @thelamer, one question. How did you compile melonDS to web assembly?

**Comment by thelamer** [comment]
All source is in that retrostash repo I linked before https://github.com/linuxserver/emulatorjs/issues/24#issuecomment-1015800744 but melon builds without any changes at head I believe.

Again here are the notes for threaded mode https://github.com/thelamer/RetroArch/tree/emscripten-tweaks/pkg/emscripten

**Comment by ethanaobrien** [comment]
@thelamer I found a speed hack for loading states. You might want to check this out. (I also have a speed hack for saving but its more javascript based than C based)

https://github.com/ethanaobrien/RetroArch/commit/a0b31976db611984c091d96fc97aa3f8e76205f4#diff-2054bb924e46ae98796b998b68056fe6feb3674cfe114a42314a6bf3ee74c45bR69

**Comment by thelamer** [comment]
Really cool stuff, does most of the benefit come from not zipping the files?
Surprised you are allready hacking raw C code after a couple weeks, crazy.
Keep it up 👍

**Comment by ethanaobrien** [comment]
>Really cool stuff, does most of the benefit come from not zipping the files?

Actually, retroarch seems to limit the read/write speed so to save I read straight from the ram (see [this](https://github.com/ethanaobrien/RetroArch/blob/master/tasks/task_save.c#L1478) along with [this](https://github.com/ethanaobrien/emulatorjs/blob/main/data/emu-main.js#L4186) (you would need to [export `getValue`](https://github.com/ethanaobrien/RetroArch/blob/master/Makefile.emscripten#L67)))
With the load files I just bumped up the chunk size and it loaded crazily faster!

>Surprised you are allready hacking raw C code after a couple weeks, crazy.
Keep it up 👍

Thank you!

**Comment by ethanaobrien** [comment]
@thelamer Quick question, When compiling for `gearboy`, It compiles correctly, but when I try to run it I get the error
```
RuntimeError: null function or function signature mismatch
```
Do you know what might be wrong?
[localhost-1645483870032.log](https://github.com/linuxserver/emulatorjs/files/8112458/localhost-1645483870032.log)

**Comment by thelamer** [comment]
No it works for me, it has to be some of the modifications you made to the frontend. 

![af-fs8](https://user-images.githubusercontent.com/1852688/155397477-ff0ade84-322a-455f-aac1-f63cd6fb5b54.png)

You sure you did a hard reload for the cores from libretrojs that is exactly what I tested?

**Comment by ethanaobrien** [comment]
Yes, I even tried the precompiled cores [here](https://github.com/linuxserver/libretrojs/releases/tag/1.6.6) and got the same error

**Comment by thelamer** [comment]
I am not sure what to say, what I have a screenshot of is exactly the code you linked.

**Comment by ethanaobrien** [comment]
Strange. I'll try testing on another computer and let you know

**Comment by ethanaobrien** [comment]
@thelamer What version on the emsdk do you use to compile?

**Comment by thelamer** [comment]
1.39.5

Take a look over this doc again for clearer build instructions: 
https://github.com/thelamer/RetroArch/tree/emscripten-tweaks/pkg/emscripten

Keep in mind the emscripten stuff is not under heavy development upstream so they are not looping newer emsdk versions. Also if you are making optimizations or improvements try to PR them into them. (especially if you figure out wrapping their netcode in websockets as they got some of the best universal netcode) There is a dev over there ToadKing that really took the web stuff and ran with it, but it looks like it has lost focus over the last 2 years or so. The core functionality is there and for the most part you can build head emus for the simple ones just leveraging single threaded emulation.

**Comment by ethanaobrien** [comment]
Im compiling with the version of emscripten you said and it compiles fine, but I get the following error when trying to run
```
Uncaught (in promise) RuntimeError: abort(LinkError: WebAssembly.instantiate(): memory import 335 has a larger maximum size 4096 than the module's declared maximum 2048) at Error
```
do you know how I can fix this?

**Comment by thelamer** [comment]
No sorry the only thing I know about emscripten memory management is the `-s TOTAL_MEMORY` and `-s ALLOW_MEMORY_GROWTH` compile flags. When the program is started in your browser it is allocated exactly what is set for TOTAL_MEMORY, if growth is enabled it can expand beyond that at runtime. 

Though that error seems to indicate some kind of hard cap being broken. I think the limit for ram allocation on modern browsers is like 2 gigs per thread.

**Comment by ethanaobrien** [comment]
Thank you for the help, I've been doing some digging, turns out the reason it wasnt running was because of something in the frontend, although I havent been able to figure out why the nes and snes cores work yet. I'll let you know If I figure anything else out

**Comment by ethanaobrien** [comment]
@thelamer Quick question. (ok first, not sure what I was doing wrong but the ds core is working now)

Have you found that `DeSuMe` or `melonDS` works better compiled to webassembly?

**Comment by ethanaobrien** [comment]
@thelamer I was doing some digging and found a wasm n64 emulator: https://github.com/nbarkhina/N64Wasm

In the readme it speaks of some bugs that I have found in the emulatorjs n64 emulator. What are the chances this is what was used?

**Comment by thelamer** [comment]
melonds was all I got working. 
N64Wasm is forked from libretro's parallel https://github.com/libretro/parallel-n64 . 
If you are looking for an improved N64 emu I would recommend linking up with https://github.com/raz0red the maintainer of https://www.webrcade.com/ they have taken nbarkhina's code and optimized it fixing audio and such last I heard for their current staging release. https://play-staging.webrcade.com/
Though it is not open source yet. https://github.com/webrcade

**Comment by ethanaobrien** [comment]
@thelamer 
Thank you

One question,
Sometimes when compiling certain cores, I get an error saying that the function is already defined (in the `.bc` file) and is re-defined in the retroarch frontend. Did you get this error? If so how did you fix it?

**Comment by thelamer** [comment]
Have not built cores in a while and never did any modifications to the source outside of minor edits to fit for web. But I recall something about using extern for variable/function names.

**Comment by ethanaobrien** [comment]
@thelamer Great news! Thanks to @BinBashBanana I was able to compile nintendo 64 as a beta core. (Other 3D systems might work too with his patch) see https://github.com/BinBashBanana/webretro/issues/6
