### ISSUE TITLE
Suggestion : use shiragame database to manage hash/title match from nointro/redump/tosec/other

### ISSUE THREAD

**Issue by StudioEtrange** [linuxserver/emulatorjs#27]
You could use this existing database (Shiragame) to match hash and nointro/redump/other games
It is ready to use and you will not have to maintain some reference internally

https://github.com/SnowflakePowered/shiragame

Shiragame is a games and ROM SQLite database that is automatically updated twice weekly by compiling DAT files from cataloguing organizations like Redump, No-Intro, or TOSEC

shiratsu is the tool which can generates a sqlite database, it is used to generate shiragame itself https://github.com/SnowflakePowered/shiratsu

**Comment by thelamer** [comment]
The purpose of the metadata is to link a sha1 of a rom to art assets.
Are you suggesting importing this to link the names (not really used) to sha1?

**Comment by StudioEtrange** [comment]
The database will make the link between the rom and the real full game name
example from TOSEC

Equinoxe (1991)(Ubisoft)(fr)[a] <== [fr]ench [a]lternative version
Asteroids (USA) (Beta) <== [Beta] version of Asteroids for [USA] region

 sha1 can match this real full name into database

**Comment by thelamer** [comment]
I appreciate the suggestion, but am moving even more entrenched in community participation with the latest update to try to get more people to submit metadata. I want to build from this current base to have a solid art/sha link as it applies to the real world.
