### ISSUE TITLE
How to set-up in unraid docker

### ISSUE THREAD

**Issue by kiaenigma27** [linuxserver/emulatorjs#3]
Hi. 

Sorry to be a pain but I am struggling to understand how this docker image works.

When I pull the docker in unraid and install and then access the webUI all i get is a white page with version info.

If i try and access the front end using port 80 it just loads the unraid UI

is there a more detailed instruction on how to set this up?

**Comment by j0nnymoe** [comment]
You need to be remapping any conflicting ports as you would do any other container. 

Also this isn't the place for general support. For that please use our discord or forum.

**Comment by kiaenigma27** [comment]
Thank you.
