### ISSUE TITLE
N64: Contoller input mapped only for single-player

### ISSUE THREAD

**Issue by Andrewpaps** [linuxserver/emulatorjs#31]
On n64, only the 1st player has default mappings, and manually mapping 2-4 is not persistent accross sessions. Would it be possible to have the default 1st player inputs mirrored accross to the other players as default? Perhaps by pressing reset and update and then manual adjustments can be made thereafter? As is, there is no way to play local multiplayer with identical controls for each player.

**Comment by thelamer** [comment]
n64 is not code we own, as soon as there is a retroarch core available for n64 this will not be an issue.
