### ISSUE TITLE
One of my gamepad key make me quit the N64 emulator

### ISSUE THREAD

**Issue by nixxou** [linuxserver/emulatorjs#33]
I can't play N64 emulator on my PC because for each of my controller, one of their button make me quit the game. Seems like it's registered as Back into browser or something like that.

I tried with two controller, the first one is an emulated xbox controller using a DualShock 4 with DS4Win.
Since i wondered if my issue was because of an unconventional setup, i also tried with a really basic usb controller and i got the same result.
I used chrome incognito mode to use a bare config.
![IMG_20220214_142017](https://user-images.githubusercontent.com/45721836/153875083-bc900d78-92c8-4ead-9b01-20e78adff307.jpg)
If i press either O on the first controller or B in the second one, the browser seems to register it like Go Back and that quit the game
https://www.youtube.com/watch?v=d3wlhqVz0c4

And the most important, i don't have any issue when i tried to launch a n64 game using this page : https://ethanaobrien.github.io/emulatorjs/ where i can press O key all i want i don't leave the page.

**Comment by thelamer** [comment]
In my rush to provide controller support for the menu I never bothered to test it's interaction with the emulatorjs emus. (my bad)
I'll have a fix for this before EOD.

**Comment by nixxou** [comment]
As a side note, i found a dirty way to fix the issue, disabling the back feature. I popup the dev console and enter : 
 history.pushState(null, null, location.href); history.back(); history.forward(); window.onpopstate = function () { history.go(1); };

**Comment by thelamer** [comment]
There are many approaches, but the most universal will be to unbind the gamepad API before loading in the payload for emulatorjs.

**Comment by thelamer** [comment]
This is fixed in the latest release, please pull the new container.
