### ISSUE TITLE
[Feature request] Rename "Scan" to "Deep Scan" and add "Scan" button for Quick Scan

### ISSUE THREAD

**Issue by nixxou** [linuxserver/emulatorjs#35]
Let say you have few thousand of roms under zip files within you rom directory. You want to add just one.
When you click on Scan, you better be ready to have time to spare, because it's going to unzip and hash every single rom. (and you can probably add a few hours if like me you keep your roms in a gdrive mount)

Is that behavior really necessary ? I don't think so. While it's good to be able a Deep Scan for specific purpose and we should keep it, the default behavior should be a quick scan. Keep a cache, if it's the same filename + size, it's obviously the same file. Take result from cache and no need to unzip & un-hash. That way, if you drop a rom in a folder with 5000 roms and launch a scan, it will be over 5000 time faster. For me, that would be an huge quality of life improvement.

**Comment by thelamer** [comment]
In the latest version you can re-scan a system from the side bar, it skips all roms that are already scanned in.

**Comment by thelamer** [comment]
Also side note, if you are using gdrive you should check out https://www.webrcade.com/, they are setup to specifically leverage cloud endpoints with a zero hosted feed style solution.
