### ISSUE TITLE
please include a list of CIDs for resources

### ISSUE THREAD

**Issue by whiteowl3** [linuxserver/emulatorjs#38]
It would be awesome if the git contained an up to date list of all the CIDs used for the metadata resources so that we can feed them directly into our pinset management system of choice without fiddling with the json.  this would make mirroring your resources a trivial for anybody who wanted to.

**Comment by thelamer** [comment]
This will get pushed back a bit I have a lot on my plate the next couple months. I apologize but to just dump cids you can use: 
```
cat nes.json |jq -r '.[] | .vid, .logo | select( . != null )'
```
That can be piped into something like an ipfs add command IE: 
```
cat nes.json |jq -r '.[] | .vid, .logo | select( . != null )' | xargs -i ipfs pin add {}
```
