### ISSUE TITLE
Controller / saves settings ?

### ISSUE THREAD

**Issue by totof-l** [linuxserver/emulatorjs#4]
Hi, thanks for this great app ! 
I had lost hope for something like this to be release.

I don't know if this is a bug, a request, or something that will never happen.

For the contoller (Xbox One), the "A" and "B" button are inverted.
I know hot to change this in the Retroarch settings (and how to save it), but this settings will change if I clear my browser cache.
I suppose it's the same for the saves/states.
It's great by default, but I was wondering if there is a way to set this to be stored on the "server" side (both controller settings and saves/states settings) ?

Another question (just by curiosity, not a request), is there some plans to manages users ?
For exemple, with a user management system, my friends could play games on emulatorjs with multiple browser, and keep there saves / states.

By the way, the apps is running great, all roms are set with logo and video.

Thanks again, very great app !

**Environment :**
 - OS: UnRAID (Docker)
 - Browser: Firefox (on Windows)
 - Controller : Xbox One (on Windows)

**Comment by thelamer** [comment]
I'll reference to what I stated in this thread, https://github.com/linuxserver/docker-emulatorjs/issues/2#issuecomment-966787013 . 
The application is ground up supposed to be static web files and the user's settings (retroarch userdata directory) are stored in the browser. There is no technical limitation in having a simple backend that dumps this browser `fs` object data and does something with it, it is just that I know people like to open stuff to the internet and I don't want to be responsible for auth and user management that could potentially be a security issue. 
With the current design there is zero risk to a user's server, as these are just static files. That is what I am willing to maintain for now.

**Comment by totof-l** [comment]
Alright I understand, thanks !

**Comment by thelamer** [comment]
In the latest version there is now a file explorer icon in the top left of the interface, this allows you to manage the browser storage and download/upload full backups.
