### ISSUE TITLE
PSX shows RetroArch Quick Menu

### ISSUE THREAD

**Issue by Subtixx** [linuxserver/emulatorjs#46]
I tried the PSX emulation and all I get when the game is finished loading is the quick menu from retroarch:

![grafik](https://user-images.githubusercontent.com/20743379/166506480-a5914f2f-a6ff-427c-8af9-fe39597abb86.png)

**Comment by XanderStrike** [comment]
I think the PSX emulator doesn't support archives even though the frontend does. It happily plays `iso` and `bin` files for me but does that for zips.

**Comment by Subtixx** [comment]
That's strange since the default extension in frontend is zip and not iso nor bin. Hopefully this gets fixed.

**Comment by thelamer** [comment]
I highly recommend CHD for all CD based systems. It is the highest compression and will just work. 

```
for i in *.cue; do chdman createcd -i "$i" -o "${i%.*}.chd"; done
```
chdman is in the container if you don't have it sys level just exec in and convert away.

**Comment by XanderStrike** [comment]
Holy crap you weren't kidding about compression, it even slightly edges out 7zip for 1435 PSX roms:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1565303/167454554-8902868d-8d94-43ef-9331-867454b5b0fa.png">

It also happily handled multi-track bins that didn't work before which is awesome. Definitely switching to this going forward, seems to work with every game I try now.

One downside, I just let it run for 19 hours compressing my bins to CHDs, and now the scan script is extracting (and in some cases using binmerge to further split) all of them. This means the scan takes ages. Is there any reason we can't hash the whole CHD?

**Comment by thelamer** [comment]
@XanderStrike yeah it sucks, in general the rom identification I use shas and reference no-intro and redump.org. 
And depending on the system I need to use know specific track shas for what is inside the CHD, just summing the whole file would not be effective as it can produce different results depending on compression level and underlying system. So you actually need the raw tracks and the only way to do that is to extract the CHD image and sum the contents inside of it. 
For zipped roms we can potentially use the CRC references as that is stored as meta data in the zip itself see: 
https://github.com/linuxserver/emulatorjs/issues/36
But all our database is referenced of sha1 sums so would need to convert them over and the users zips would need to be clean (which I am finding is rarely the case as releases usually have readmes or nfos of some kind in them) Also you take stuff like NES roms they need to have their header stripped away to reference no-intro db entries. 
I am down with improving speed and reducing the burden of scanning in roms, but in general leaning more towards lower code maintenance vs high optimized scanning options.

**Comment by ltomes** [comment]
If you move to CRC, would it be incremental/start with a flag or setting to allow 'fast' scanning?

Maybe something like:

`metadata/crc_<plaform>.json`
Direct lookup of a crc hash, to a uuid entry in playform.json
`metadata/sha1_<plaform>.json`
Direct lookup of a sha1 hash, to a uuid entry in playform.json
`metadata/<plaform>.json`
Same as now, but keys are a uuid instead of sha1

Would result in one more direct lookup/reasonable complexity, but a pretty maintainable structure.

**Comment by Xeddius** [comment]
I'd love for emulatorjs to have a setting/toggle so it doesn't scan files that it already has an existing checksum for.

**Comment by ltomes** [comment]
> I'd love for emulatorjs to have a setting/toggle so it doesn't scan files that it already has an existing checksum for.

I believe that exists if you "Scan for new Roms", at least to me it looks like it skips files it already scanned.

<img width="152" alt="image" src="https://user-images.githubusercontent.com/4184677/174679955-95f1fdad-1966-46cc-bfbc-cf5bb3a27801.png">

**Comment by Xeddius** [comment]
@ltomes I see, thank you, I hadn't realized it was there.
