### ISSUE TITLE
Created Profile, but not seeing cross browser saves

### ISSUE THREAD

**Issue by MonotoneCulprit** [linuxserver/emulatorjs#47]
Created a Profile to test using the same saves across multiple devices. Saves do not seem to be saving server side even with the profile.

**Comment by thelamer** [comment]
its a manual push pull process, you need to click on the file icon in the web interface and while in that menu login to your profile and push to the server. Same process for pulling to a client.

**Comment by MonotoneCulprit** [comment]
Alright so I'm not going crazy then. I never get the option to login which is why I can't do the manual push/pull. I'll nuke my container and rebuild. Hopefully then I'll see the login option. Thank you for the quick response.

**Comment by MonotoneCulprit** [comment]
So it looks like the issue is that /frontend/profile doesn't exist so it's throwing a 404. This is, I believe, causing the login box to be hidden. I am able to see the login box by assigning it the left class, but it doesn't actually do anything because of the 404. 

Going to try creating that folder and moving the source code in manually and see if that helps

**Comment by MonotoneCulprit** [comment]
It was a me problem. Maybe the Websocket would connect if I told my reverse proxy to allow Websockets. Closing this. Thank you again.
