### ISSUE TITLE
Genesis roms give: No cue found error

### ISSUE THREAD

**Issue by LeifAndersen** [linuxserver/emulatorjs#49]
4 of the roms located in the Sega Genesis Collection on steam: https://store.steampowered.com/agecheck/app/34270/ have .bin as their file extension. One example is sonic3&knuckles: Sonic_Knuckles_wSonic3.bin

However, since this isn't a cd there isn't a cue file. The rom scanner doesn't seem to realize it though, and gives the following output:

```
No cue found
processing Sonic_Knuckles_wSonic3.bin 
```

This is a good rom (or at least it runs in both retroarch as well as the collection's built in emulator). 

So maybe its worth scanning .bin files even if their aren't cue files?

**Comment by thelamer** [comment]
I would zip them, unfortunately the logic as it exists assumes a .bin file is a cd image and looks for it's accompanying cue file.

**Comment by Protektor-Desura** [comment]
Try renaming them from .bin to .md and see if they get recognized that way, since Sega Mega Drive/Genesis roms end in .MD usually.
