### ISSUE TITLE
cant load js/vendor/hammer.min.js.map

### ISSUE THREAD

**Issue by Festeazy** [linuxserver/emulatorjs#5]
I started this using docker and have decent docker experience. 
it loads up fine and i can scroll through different game consoles but when i select one, i get a black screen because it cant load something

Below is the web browser console information along with a screenshot

evTools failed to load source map: Could not load content for http://192.168.0.90:8011/js/vendor/hammer.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://192.168.0.90:8011/js/vendor/browserfs.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
default.png:1 GET http://192.168.0.90:8011/user/undefined/backgrounds/default.png 404 (Not Found)
Image (async)
attr @ jquery.min.js:2
$ @ jquery.min.js:2
attr @ jquery.min.js:2
(anonymous) @ index.js:72
later @ index.js:25
setTimeout (async)
(anonymous) @ index.js:29
rendermenu @ index.js:294
async function (async)
rendermenu @ index.js:212
(anonymous) @ index.js:414
Promise.then (async)
loadjson @ index.js:413
window.onload @ index.js:425
load (async)
(anonymous) @ index.js:418
:8011/user/undefined/corners/default.png:1 GET http://192.168.0.90:8011/user/undefined/corners/default.png 404 (Not Found)
Image (async)
attr @ jquery.min.js:2
$ @ jquery.min.js:2
attr @ jquery.min.js:2
(anonymous) @ index.js:73
later @ index.js:25
setTimeout (async)
(anonymous) @ index.js:29
rendermenu @ index.js:294
async function (async)
rendermenu @ index.js:212
(anonymous) @ index.js:414
Promise.then (async)
loadjson @ index.js:413
window.onload @ index.js:425
load (async)
(anonymous) @ index.js:418
inpage.js:1 MetaMask: MetaMask will soon stop reloading pages on network change.
For more information, see: https://docs.metamask.io/guide/ethereum-provider.html#ethereum-autorefreshonnetworkchange 
Set 'ethereum.autoRefreshOnNetworkChange' to 'false' to silence this warning.

![image](https://user-images.githubusercontent.com/65983438/141873078-b799f20a-c1d3-4a08-9627-f4c37a96cdbe.png)

**Comment by thelamer** [comment]
Use the backend to scan in the games you added. Take a moment to read the instructions. The steps are outlined.
Also please use discord for support.
