### ISSUE TITLE
Custom Metadata nes.json

### ISSUE THREAD

**Issue by coffinbearer** [linuxserver/emulatorjs#50]
https://www.textdrop.link/#/QmagGSjpVd3CkTFHBGQzu1WWiUgNwvAWsVsSTiysCaEo7H
https://anonfiles.com/t5ifb3l2y9/nes_logos_zip
https://anonfiles.com/n2n4b0l2yf/nes_videos_zip

hope it helps.

**Comment by coffinbearer** [comment]
@thelamer yes i still have all the reference data, what do you need?

**Comment by thelamer** [comment]
@coffinbearer sorry again for the delay, The anon files expired can you re-up so I can seed them out on some IPFS nodes ?

**Comment by coffinbearer** [comment]
@thelamer sure here you go:
https://anonfiles.com/LcQbO4peyb/nes_logos_zip
https://anonfiles.com/R6d0Pap7y1/nes_videos_zip

if you prefer a different hoster, just tell me which one.

**Comment by thelamer** [comment]
@coffinbearer I don't get it they are both 404 IE: 
https://cdn-112.anonfiles.com/LcQbO4peyb/6953d3f6-1655311202/nes_logos.zip
https://cdn-107.anonfiles.com/R6d0Pap7y1/e6a0578f-1655311212/nes_videos.zip

**Comment by coffinbearer** [comment]
@thelamer here a different hoster:
https://www.filemail.com/d/eqcwczhqjmsfanj

**Comment by thelamer** [comment]
@coffinbearer thanks so much, I have the files pinned out to some nodes. I will work on getting this merged into the nes metadata in the next release. 

Thank you for not only taking the time to up all this stuff but bearing with me in this ticket after all this time. 

I'll ping and close when this has been cut.

**Comment by thelamer** [comment]
New release has been cut with the added nes metadata.
Thanks again @coffinbearer only 30 more systems to go 😃
