### ISSUE TITLE
Question Support of Commodore? Amiga C64? would be a nice Goal

### ISSUE THREAD

**Issue by raindancer2204** [linuxserver/emulatorjs#54]
Hello,

I have to tell you that is really a great project what you have Hats off!

The whole thing is still in Docker, what more could you ask for.

But one requirement I would have liked as many would still like the Commodore support.

Can you possibly support/implement Amiga 500 or Commodore C64 emulation?

Greetings and keep it up!

Raini

**Comment by lukebevan01** [comment]
agreed, C64 would be amazing

**Comment by raindancer2204** [comment]
Hello,
I currently pulled the Docker image from April 1st. By when will the Amiga or C64 be on the roadmap? :)
Is there a statement about it? Would be happy I still belong to the C64 generation.

Thank you

**Comment by raindancer2204** [comment]
Hello dear developers, is there already someone who is pushing the topic of Commondore? Would be really great! :) A great project.
