### ISSUE TITLE
[Bug] Issue navigating to psx page from rom management page.

### ISSUE THREAD

**Issue by ltomes** [linuxserver/emulatorjs#59]
While on the `Rom Management` page, attempting to navigate the the `psx` page results in the following error for me:
```
triggerUncaughtException(err, true /* fromPromise */);
^

[Error: EISDIR: illegal operation on a directory, read] {

errno: -21,
code: 'EISDIR',
syscall: 'read'
}
```

This could be related to https://github.com/linuxserver/emulatorjs/pull/58 not yet being merged. I am not sure.

**Comment by Xeddius** [comment]
I had this issue earlier today, I solved it by switching to CHD format as I had games in .7z format and this exact problem was happening to me until I converted the .bin/.cue into CHD, it's also slightly smaller as CHD anyway and is the new standard format for compressing most iso/bin games.

**Comment by ltomes** [comment]
I'm hoping PR 58 resolves the zip archives having issues (I tracked my failures down to a zip archive), and based on what you are saying it sounds like that will maybe resolve this issue.
But it could be the bin format inside like you are saying. I can look into that next if the 58 doesnt fully resolve things.


Randy Linden gave permission to use one of his ROMs in integration tests so, after this is fixed I may try to add a simple test harness that runs some of these shell scripts in isolation and asserts non 0 exit codes against 
7zip, rar, and zip archives.
https://twitter.com/RandalLinden/status/1538965024932171776

**Comment by Xeddius** [comment]
I look forward to it, keep me updated!

**Comment by ltomes** [comment]
> I had this issue earlier today, I solved it by switching to CHD format as I had games in .7z format and this exact problem was happening to me until I converted the .bin/.cue into CHD, it's also slightly smaller as CHD anyway and is the new standard format for compressing most iso/bin games. I highly recommend it.
> 
> If you don't want to change over to CHD then you'll have to figure out which .zips/.7z/etc are causing the issue, many highly compressed .zip files cause problems.

I have not switched formats yet, but see the failed to decompress issues you describe. That error is in the psx emulator baked into emulator js right? It's not part of this repo?

**Comment by MainServerSpace** [comment]
Use chdman very easily process I did it for all mine and it works great. Great to see my original coming to use
