### ISSUE TITLE
Rom Scan Fails exited with code: 2

### ISSUE THREAD

**Issue by diskkonnected** [linuxserver/emulatorjs#6]
I have run into the below issue using different roms. Not sure if its a naming or hashing issue. But it will scan some and then fail.

Scan exited with code: 2
printf: usage: printf [-v var] format [arguments]
panic: Unable to find NES magic. goroutine 1 [running]: main.main() /NES20Tool/NES20Tool.go:344 +0x31a5
Loading ROM: /data/hashes//nes/roms//tmp/Bases Loaded (USA).nes
hashing Bases Loaded (USA).zip
unzipping Bases Loaded (USA).zip
Loading ROM: /data//nes/roms//Baseball Stars II (USA).nes

**Comment by thelamer** [comment]
Rom scanning for NES uses NES20Tool, looks like that rom is lacking headers that should be present on every rom. I have yet to run into files without headers yet.

**Comment by thelamer** [comment]
I have set NES roms to fallback to a shasum if it does not have a proper header.
