### ISSUE TITLE
EmulatorJS show "No items to load, please add some games" 

### ISSUE THREAD

**Issue by zDEFz** [linuxserver/emulatorjs#62]
Steps done

1. Visited http://192.168.178.31:3000/
2. Added N64 ROMS
3. Scanned N64 ROMS, added Artwork
4. Visited  http://192.168.178.31:3001/
5. Got message "No items to load, please add some games"
6. Searched in the Wiki or on the EmulatorJS page but found no proper guide or documentation

**Comment by deepio** [comment]
Browser data, clear all cookies and site data and visit it again or try in incognito mode.

**Comment by Bunto86** [comment]
I have the same issue and followed your instructions and got it to work incognito mode. Is there any way to get it to work without incognito mode?

**Comment by zDEFz** [comment]
Yea it makes no sense. I consider this a limitation as it happened at the first-time-use.

**Comment by drewschbag** [comment]
Just clear your browser cookies/history and move on. This ticket should be closed. No dev support is needed on this.
