### ISSUE TITLE
More consoles supported?

### ISSUE THREAD

**Issue by Protektor-Desura** [linuxserver/emulatorjs#65]
I thought I might point out someone else who is using emscripten to do the same thing but they got Fairchild F and Atari 5200 from Libretro compiled for Javascipt from emscripten.

https://github.com/BinBashBanana/webretro

They support:
**81-libretro**
**a5200 (Atari 5200)**
Beetle NeoPop (Neo-Geo Pocket)
Beetle PSX HW (PlayStation)
Beetle VB (Virtual Boy)
Beetle WonderSwan (WonderSwan)
**FreeChaF (Fairchild Channel F)**
FreeIntv (Intellivision)
Gearcoleco (ColecoVision)
Genesis Plus GX (Sega Systems)
Handy (Atari Lynx)
melonDS (Nintendo DS)
mGBA (GB/GBC/GBA)
Mupen64Plus-Next (Nintendo 64)
NeoCD (Neo-Geo CD)
Nestopia UE (NES)
O2EM (Odyssey 2)
Opera (3DO)
ParaLLEl N64 (Nintendo 64)
ProSystem (Atari 7800)
Snes9x (SNES)
Stella 2014 (Atari 2600)
Vecx (Vectrex)
Virtual Jaguar (Atari Jaguar)
Yabause (Sega Saturn)

Here is an enscriptem version of ScummVM as well:
https://github.com/juj/emscripten-scummvm
https://github.com/gr33k/emscripten-scummvm
https://github.com/miracle2k/emscripten-scummvm (Has a docker version & a couple of updates)

**Comment by markusbkk** [comment]
Just chiming in about that ScummVM comment.

The forks linked above are a bitch to compile on a modern OS.
Thankfully, there's [upstream support now](https://github.com/scummvm/scummvm/tree/master/dists/emscripten), as well as a [bug tracker](https://github.com/chkuendig/scummvm-demo/tree/main/games) hosted by the original porter.
