### ISSUE TITLE
Multi-Disc Support?

### ISSUE THREAD

**Issue by LostOnTheLine** [linuxserver/emulatorjs#66]
The config for the systems has an option for `    "multi_disc": 0` but no way within the interface to turn the multi-disc on or off. 

In the readme it says
```
The only web emulators that supports multiple CD games are psx and saturn, in order to function please rename your chd files before scanning them in to the same name with the extension .disk1,.disk2,.disk3,etc. IE:

/data/psx/roms/GAMENAME.disk1
/data/psx/roms/GAMENAME.disk2
/data/psx/roms/GAMENAME.disk3
```

but when I rename files in `segaSaturn/roms/` this way I get the errors 
```
Filetype disk2 not supported
Filetype disk1 not supported
Filetype disk2 not supported
Filetype disk1 not supported
```

When I rename them to `.disk1.chd` & `.disk2.chd` they end up as `Unidentified Roms:`
Manually matching them leaves 2 entries for the title like before I removed them, renamed & re-added them.

**Comment by kamilkrzywda** [comment]
disk1.zip/disk1.7z etc, not just disk1

**Comment by brunoccr** [comment]
Original format is CUE and BIN, I understood that it only works when you convert the CUE and BIN to CHD and change .chd to .disk1 and ........ works

**Comment by mattthhdp** [comment]
Could you expand a little  
![image](https://user-images.githubusercontent.com/10604324/222931248-cf7bad23-d63b-4c5a-bdec-f8b2f1987631.png)
 this dosent detect disk 2 and 3 this is the error emulatorjs give me when scanning
![image](https://user-images.githubusercontent.com/10604324/222931297-7e73d552-21bf-4ae1-9031-165be2e53313.png)

**Comment by webysther** [comment]
Same problem, with chd files not working too. Tried? GAME.chd.disk1 and GAME.disk1.

![image](https://github.com/linuxserver/emulatorjs/assets/750007/d8776d78-7164-4031-9ff6-9a9d75d6ee75)

![image](https://github.com/linuxserver/emulatorjs/assets/750007/a6ed2a5c-2e93-487b-b40c-cc5d512f3ec1)

```
Scan exited with code: 0
Filetype disk2 not supported
hashing Resident Evil 2 (USA).disk1 (Track 1)
[INFO] Output directory: /data/hashes/psx/roms/tmp/split [INFO] Opening cue: /data/hashes/psx/roms/tmp/FILE.cue [INFO] Splitting files... [INFO] Wrote 2 bin files [INFO] Wrote new cue: /data/hashes/psx/roms/tmp/split/FILE.cue
Resident Evil 2 (USA).disk1 is multi track need to split
Extraction complete
Extracting, 94.3% complete...
Extracting, 91.9% complete...
....
Extracting, 0.0% complete...
Output TOC: /data/hashes//psx/roms//tmp/FILE.cue Output Data: /data/hashes//psx/roms//tmp/FILE.bin Input CHD: /data/psx/roms//Resident Evil 2 (USA).disk1
chdman - MAME Compressed Hunks of Data (CHD) manager 0.224 (unknown)
processing Resident Evil 2 (USA).disk1
```

There a restriction to not use m3u playlist?
