### ISSUE TITLE
[REQUEST] Delete all ROMs without available art

### ISSUE THREAD

**Issue by dacaz5** [linuxserver/emulatorjs#7]
I was just wondering if we could get the capability to easily delete all ROMs that it can't find art for, to make it easier to dump a bunch of ROMs in the system and if any don't match to just get rid of them.

**Comment by thelamer** [comment]
I will implement a third button outside of the add all roms to config to only add ones that have at least a video and a logo as that is a complete art set.

**Comment by thelamer** [comment]
Latest version has implemented a button to remove all roms from a config that don't have all art assets. Please update your container.
