### ISSUE TITLE
i cant download data

### ISSUE THREAD

**Issue by jok3r007** [linuxserver/emulatorjs#71]
i cant link ipfs to download thre files of data ,why?

**Comment by thelamer** [comment]
So Infura shut down their public IPFS gateway and api to upload files I need to at some point remove this from the codebase. 
The core asset downloading works as it uses native IPFS but the web based profile backup etc is now depricated.

**Comment by jok3r007** [comment]
I cant understand it ,can you give me the files

**Comment by Xeddius** [comment]
I need a way to download the configs, is there another source where the files can be found?
