### ISSUE TITLE
[Feature Request] Server Save Handling/Cloud Saves

### ISSUE THREAD

**Issue by KingIzzymon** [linuxserver/emulatorjs#75]
# Server Save Handling/Cloud Saves

I'm creating this issue to see if anyone has an problem with this idea before I continue further development.

## Goals

This feature is to essentially enable cloud saves but to your own server. This allows you to save & logout on your Xbox then login on your phone, Steam Deck or other device to pickup where you left off.

## To-Do

* Adding a login button next to the full screen button to open login form
* Login data handled via script sourced from the `filebrowser.js` login feature
* Upon login/logout, give the option to pull saves from the server or push local saves to the server

**Comment by thelamer** [comment]
This is already in the project. Check the profiles tab from the admin UI.

**Comment by KingIzzymon** [comment]
@thelamer I think you're misunderstanding me.

My goal is to make it as stream lined as possible for something like the SteamDeck and not have to dig back thru admin pages and just have the login form appear from the nice looking front end.
