### ISSUE TITLE
Can't scan Atari 2600 games

### ISSUE THREAD

**Issue by pto199** [linuxserver/emulatorjs#76]
When I try to scan them it says no .cue file found.  All the roms are in .bin and they do not have .cue files (or at least none of the romsets I could find).

is .cue file needed?  

On another note, why is Atari 5200 not supported on the LinuxServer version but is supported on the main emulatorjs version?

**Comment by charles-spurgeon** [comment]
+1

Can't scan 2600, 7800, or 32x

**Comment by blok82** [comment]
Hi!
I had the same issue.  After renaming every file from .bin to .a26 the scanning worked
