### ISSUE TITLE
Feature request: keyboard shortcuts to navigate large rom libraries quicker

### ISSUE THREAD

**Issue by burkasaurusrex** [linuxserver/emulatorjs#8]
Can't say enough how cool this is! All around great idea, great execution.

Just an idea - for large rom libraries, it is a bit cumbersome to navigate to specific games. It would be helpful to bind `PgUp` and `PgDn` to skip some defined number or percent of ROMs in the config. Ideally, it would be awesome to type specific characters like `t` to navigate to ROMs that start with the same letter.

**Comment by thelamer** [comment]
This is on my radar, basically as I only use this on my Xbox Series S I want to keep the concept of menu navigation being only the four arrow directions. 
Double tap did not work out well I have been playing with when the keypress is held implementing a skip feature so it goes progressively faster the longer it is held. 
I have been distracted lately with Safari support for Libretro cores though, gonna be most of my time for the near future.

**Comment by thelamer** [comment]
The latest version has implemented changes to increase mouse scroll speed, touch screen panning, and when using the up and down you can hold right to 10x the speed of the scroll.
