### ISSUE TITLE
Subfolder Rom Import

### ISSUE THREAD

**Issue by Drumhavoc** [linuxserver/emulatorjs#81]
The current import system requires roms to be in the root folder, i.e. data/snes/roms/Aladdin (USA).cfs however, my library is organized as data/snes/roms/Aladdin [1993]/Aladdin (USA).cfs.  In the Rom Management, under SNES, it shows Roms: 11 Scanned: 0 and pressing Scan returns nothing.  I am sure I am not the only one that organizes their library this way as it helps keep multi disc files together and bin and que files together as well as for naming where the release year can be added without adding it to the file name itself. 
As a test, I scanned in a file in the root directory and added it to the config file, then moved it back into a subfolder and updated the config to include the sub folder (from "Aladdin (USA).cfs" to "Aladdin [1993]/Aladdin (USA).cfs") and the file file continued to launch and work in the front end.  However, when I go back to scan new roms, it disappears (now that it is in the sub folder) and gets rid of it in the config file.
In the end, it seems that it will already work with a sub folder organization, it just needs a way to scan the files in a sub folder then put the path in the config.  I know this seems like a superficial ask, but I would greatly benefit as I am sure many others would as well.  Thanks for and amazing project!

**Comment by smidley** [comment]
I would also like to see this implemented as my files are organized the same way.

**Comment by cmoore-mayesh** [comment]
Would love to see this as a possibility as well.

**Comment by Jodge65** [comment]
I'm also interested in this feature.
I also add  that it may allow to fix the way the application count the number of rom, because it's considere every folder as a rom itself, but failed to scan them.

**Comment by hellupline** [comment]
what I do for the file structure is:
I mount the roms folder into /volumes/roms

and use symlink to map files into correct rom folder

in my case:

```ln -sr volumes/roms/Super\ Nintendo data/snes/roms```

but u can link files separately
