### ISSUE TITLE
iOS: not working

### ISSUE THREAD

**Issue by Veda82** [linuxserver/emulatorjs#82]
Hello,

I installed the container in TrueNAS Scale. Everything looks good on PC and Android (Chrome in both cases).

However, on a jailbroken 2018 iPad Pro with iOS 13.5 I cannot get it to work. Tried with both Safari and Chrome.
Virtual gamepad is showed but apparently the game is not loaded, showing only a black screen.

Any advices? Thanks in advance.

**Comment by Veda82** [comment]
Hello? Any suggestions?

**Comment by rothgar** [comment]
I have the same issue on iOS. I only checked a handful of roms that worked on my computer but would load to a black screen on my iPhone (not jailbroken)

I managed to get n64 mario cart 64 to load and started to play but the joystick didn't work.
