### ISSUE TITLE
PSX chdman error when hitting the scan button 

### ISSUE THREAD

**Issue by alphatsui** [linuxserver/emulatorjs#83]
Scan exited with code: 2

/usr/local/bin/chdman: line 2: syntax error near unexpected token `<' /usr/local/bin/chdman: line 2: ` '

/usr/local/bin/chdman: line 1: html: No such file or directory

processing Ape Escape (USA).chd

Please advise how to fix. Thanks a lot

**Comment by Womabre** [comment]
> Scan exited with code: 2
> 
> /usr/local/bin/chdman: line 2: syntax error near unexpected token `<' /usr/local/bin/chdman: line 2: ` '
> 
> /usr/local/bin/chdman: line 1: html: No such file or directory
> 
> processing Ape Escape (USA).chd
> 
> Please advise how to fix. Thanks a lot

Having the same issue...

**Comment by Hypertoken** [comment]
> Scan exited with code: 2
> 
> /usr/local/bin/chdman: line 2: syntax error near unexpected token `<' /usr/local/bin/chdman: line 2: ` '
> 
> /usr/local/bin/chdman: line 1: html: No such file or directory
> 
> processing Ape Escape (USA).chd
> 
> Please advise how to fix. Thanks a lot

Same here... Interesting; when I cat the contents of chdman its an html file. 
Maybe the source where chdman is pulled is getting slammed for requests?

```
root@8d3e8300a47b:/usr/local/bin# ls
NES20Tool  binmerge  chdman
root@8d3e8300a47b:/usr/local/bin# cat chdman
<html>
<head><title>429 Too Many Requests</title></head>
<body>
<center><h1>429 Too Many Requests</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

**Comment by Hypertoken** [comment]
Upon further research, looks like the source where chdman is pulled is no longer valid; **https://ipfs.infura.io** changed to **https://infura-ipfs.io**

```
echo "**** grab pre-built chdman ****" && \
  curl -L \
    "https://ipfs.infura.io/ipfs/QmUfYfuoxPgDRc9Mniv1TBXv6LXPRNArAabZo5VnzfZNtP" \
    -o /usr/local/bin/chdman && \
  chmod +x /usr/local/bin/chdman && \
  echo "**** cleanup ****" && \
```
I just ran;

```
curl -L "https://infura-ipfs.io/ipfs/QmUfYfuoxPgDRc9Mniv1TBXv6LXPRNArAabZo5VnzfZNtP" -o /usr/local/bin/chdman
chmod +x /urs/local/bin/chdman
```
Now I can scan PSX, I'll come back and let you know if its working.

**Comment by Hypertoken** [comment]
Ok, so this seems to be an issue with the docker version (which I am using). However they seem to have already fixed the issue on their end [4 months ago](https://github.com/linuxserver/docker-emulatorjs/commit/bfec082893bf2d08234fe0b278b72aeb8ab6356f); so I'm not sure why I'm getting this issue now. I pulled the "Latest" maybe its not yet updated.

**Comment by Bidonh** [comment]
No it's not fixed, I just tried the linuxserver/emulatorjs:1.7.2-ls53 container and I still got a chdman error.
```
Scan exited with code: 2

/usr/local/bin/chdman: line 2: syntax error near unexpected token `<' /usr/local/bin/chdman: line 2: ` '  

html: No such file or directory

/usr/local/bin/chdman: line 1:

processing game.chd

```

While the linuxserver/emulatorjs:1.7.2-ls42 released [**Sep 3, 2022**](https://github.com/linuxserver/docker-emulatorjs/releases/tag/1.7.2-ls42) works great.
Except for IPFS daemon cpu+bandwidth usage...
