### ISSUE TITLE
looking for a frontend solution on Android TV 

### ISSUE THREAD

**Issue by shahram7** [linuxserver/emulatorjs#87]
Hello everyone,
I'm not here to report an issue. I just need to ask for some suggestions.
I installed emulatorjs with docker from linuxserver on my proxmox homeserver.
Now I want to play on my Android TV, but the native web browser installed on my Bravia makes it impossible.
I just wanted to ask if there is an android app that plays the front end roll?
Best Regards

**Comment by j0nnymoe** [comment]
No frontend for this other than the webui. You could try installing chrome and see if that improves it, otherwise you'd be better off installing retroarch.
