### ISSUE TITLE
Bug: JS paths do not reflect SUBFOLDER environment setting in backend mgmt

### ISSUE THREAD

**Issue by burkasaurusrex** [linuxserver/emulatorjs#9]
When the `SUBFOLDER` environment variable is set, the backend is accessible at `domain.com/subfolder`, but it seems to break to paths to the javascript so just a static HTML file is served.

**Comment by thelamer** [comment]
I cannot duplicate this, please read the instructions clearly and use the format IE:
```
-e SUBFOLDER='/test/'
```

**Comment by burkasaurusrex** [comment]
Ok, did a bit more testing. There's an issue when navigate to `domain.com/test` but no issue when I navigate to `domain.com/test/`

**Comment by thelamer** [comment]
yeah that would be a subfolder then, I don't have plans to change that behavior. Feel free to PR in a solution if you have one.

**Comment by aptalca** [comment]
@burkasaurusrex our reverse proxy conf has a redirect for that:
https://github.com/linuxserver/reverse-proxy-confs/blob/master/emulatorjs.subdomain.conf.sample#L43-L45
